### ISSUE TITLE
java.awt.print.PrinterException: Cannot find printer under the JavaFX libraries

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1019]
On MacOS, recently added printers cannot be found in JavaFX.
1. Download and install [Epson TM-series](https://download.epson-biz.com/modules/pos/index.php?page=prod&pcat=3&pid=6753) driver.
2. Start QZ Tray
3. Add a printer using this driver
4. Try to print to the newly added printer

Workaround:
* Restart QZ Tray

```
2022-09-06T11:23:12,638 [ERROR] Failed to print
java.awt.print.PrinterException: Cannot find printer under the JavaFX libraries
	at qz.printer.action.PrintHTML.print(Unknown Source) ~[qz-tray.jar:?]
	at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source) [qz-tray.jar:?]
	at qz.ws.PrintSocketClient.processMessage(Unknown Source) [qz-tray.jar:?]
	at qz.ws.PrintSocketClient.onMessage(Unknown Source) [qz-tray.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) [qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68) [qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:227) [qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914) [qz-tray.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by tresf** [comment]
We've getting the same thing reported on some Windows workstations.  What I'm not of is why this is so sporadic.

* On Windows, the printer reported was a Honeywell, but when installing the printer while QZ Tray was running, JavaFX found it just fine.
* Next, I tried adding a PDF printer to MacOS while QZ Tray was running, JavaFX found it just fine.
* Last, I tried adding the very Epson printer/driver in the "steps to reproduce" above, but it was found just fine.

What's not immediately obvious is why the behavior is inconsistent.  Furthemore, JavaFX will be updated in QZ Tray 2.2.3 which may impact the frequence of this issue.

I'm going to close this issue until we have steps to reproduce.
