### ISSUE TITLE
NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1055]
Oracle Java 8 and QZ Tray 2.1.6+3 won’t allow stealing the websocket
* Oracle Java 1.8.0_333 64-bit
* QZ Tray 2.1.6+3
* Windows 10 21H2 19044

Workaround: Use QZ Tray 2.2.1

```
2022-12-13T15:12:28,038 [DEBUG] Message: {"call":"websocket.stop","challenge":"AAAO\/ZHwT0UAAAAAAAAAAA=="}
2022-12-13T15:12:28,046 [INFO] Another instance of QZ Tray is asking this to close
2022-12-13T15:12:28,047 [INFO] Attempting to validating challenge: AAAO/ZHwT0UAAAAAAAAAAA==
2022-12-13T15:12:28,048 [ERROR] Connection error
java.lang.RuntimeException: Cannot call method public void qz.ws.PrintSocketClient#onMessage(org.eclipse.jetty.websocket.api.Session, java.io.Reader) with args: [org.eclipse.jetty.websocket.common.WebSocketSession, org.eclipse.jetty.websocket.common.message.MessageReader]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.unwrapRuntimeException(CallableMethod.java:93) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:75) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.lambda$onTextFrame$1(JettyAnnotatedEventDriver.java:270) ~[qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[qz-tray.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_333]
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at qz.utils.SystemUtilities.validateSaltedChallenge(Unknown Source) ~[qz-tray.jar:?]
	at qz.ws.PrintSocketClient.processMessage(Unknown Source) ~[qz-tray.jar:?]
	at qz.ws.PrintSocketClient.onMessage(Unknown Source) ~[qz-tray.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_333]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) ~[qz-tray.jar:?]
	... 5 more
2022-12-13T15:12:28,050 [INFO] Connection closed: 1011 - Cannot call method public void qz.ws.PrintSocketClient#onMessage(org.eclipse.jetty.websocket.api.Session, java.io.Reader) w
2022-12-13T15:12:28,050 [INFO] Closing all communication channels for An anonymous request
```

**Comment by tresf** [comment]
Reproduced on Java 8u361.  This is documented very well here: https://stackoverflow.com/a/61267496/3196753

> After searching for a while and verified through switching the installed JDK between 8 and 11, I have found that there are some changes (new overridden methods) applied to several methods (e.g. flip(), clear() ) in ByteBuffer class.
> 
> In Java 8, while calling flip() method of ByteBuffer class, since it has no implementation for this method, so it is actually calling the method from extended class, Buffer; which is returning Buffer object as below:
> 
> In Buffer class: [...]

**Comment by tresf** [comment]
If anyone needs a build of QZ Tray 2.1.6 with this patch, please reach out to support@qz.io.
