### ISSUE TITLE
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1061]
Using PDF rotation with headless seems to throw this exception.

To reproduce on a non-headless environment:

```bash
export QZ_OPTS="-Djava.awt.headless=true"
/opt/qz-tray/qz-tray --headless
```

```
qz_1               | No X11 DISPLAY variable was set, but this program performed an operation which requires it.
qz_1               |    at qz.printer.action.PrintRaw.parseData(Unknown Source) ~[qz-tray.jar:?]
qz_1               |    at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source) ~[qz-tray.jar:?]
qz_1               |    at qz.ws.PrintSocketClient.processMessage(Unknown Source) ~[qz-tray.jar:?]
qz_1               |    at qz.ws.PrintSocketClient.onMessage(Unknown Source) ~[qz-tray.jar:?]
qz_1               |    at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
qz_1               |    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
qz_1               |    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
qz_1               |    at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) ~[qz-tray.jar:?]
qz_1               |    at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68) ~[qz-tray.jar:?]
qz_1               |    at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.lambda$onTextFrame$1(JettyAnnotatedEventDriver.java:270) ~[qz-tray.jar:?]
qz_1               |    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[qz-tray.jar:?]
qz_1               |    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[qz-tray.jar:?]
qz_1               |    at java.lang.Thread.run(Unknown Source) ~[?:?]
qz_1               | Caused by: java.awt.HeadlessException:
qz_1               | No X11 DISPLAY variable was set, but this program performed an operation which requires it.
qz_1               |    at sun.java2d.HeadlessGraphicsEnvironment.getScreenDevices(Unknown Source) ~[?:?]
qz_1               |    at qz.printer.action.PrintImage.rotate(Unknown Source) ~[qz-tray.jar:?]
qz_1               |    at qz.printer.action.PrintRaw.getWrapper(Unknown Source) ~[qz-tray.jar:?]
qz_1               |    at qz.printer.action.PrintRaw.getPdfWrapper(Unknown Source) ~[qz-tray.jar:?]
qz_1               |    ... 13 more
```

**Comment by tresf** [comment]
Tested,https://github.com/qzind/tray/pull/1119 seems to be working, merged.
