### ISSUE TITLE
Unable to start JavaFX service

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#1075]
We have had several users/clients bring up this issue, and upgrading to the latest 2.2.x version of QZ-Tray usually fixes it, but it still interrupts service for those users.

Note: We have not been able to reproduce the issue locally, and while we have offered to troubleshoot remotely, we do not yet have access to a machine with this problem. I'm hoping that once we do, we can confidently offer an explanation along with the resolution.

A company branded version of QZ-Tray (2.2.0) started encountering this on MacOS Monterey, starting on September 23, 2022 (we just learned of this issue today):

* Macbook pro (arch unknown)
* macOS Monterey 12.6
* QZ Tray 2.2.0 (company branded)

```
2022-09-23 06:48:12,826 [ERROR] Failed to print
java.lang.UnsupportedOperationException: Unable to start JavaFX service
	at qz.printer.action.PrintHTML.parseData(Unknown Source)
	at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:227)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: JavaFX did not start
	at qz.printer.action.WebApp.initialize(Unknown Source)
	... 13 more

```

**Comment by tresf** [comment]
@lite1979 yeah this is starting to worry me as well.
