### ISSUE TITLE
Connection error when click "block"

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1132]
**Version:** 2.2.3-SNAPSHOT (`master` branch)
**Java:** 11.0.18
**OS:** MacOS 13.3

```
[DEBUG] 2023-05-22T23:06:52,247 @ qz.common.TrayManager:539
	Calculated dialog centered at: java.awt.Point[x=720,y=462]
[INFO] 2023-05-22T23:06:55,003 @ qz.common.TrayManager:503
	Denied An anonymous request to connect to QZ Tray
[ERROR] 2023-05-22T23:06:55,005 @ qz.ws.PrintSocketClient:94
	Connection error
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onEof(WebSocketSessionState.java:169) ~[websocket-core-common-10.0.12.jar:10.0.12]
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:253) ~[websocket-core-common-10.0.12.jar:10.0.12]
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onClose(WebSocketConnection.java:221) ~[websocket-core-common-10.0.12.jar:10.0.12]
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:329) ~[jetty-io-10.0.12.jar:10.0.12]
	at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:1113) ~[jetty-io-10.0.12.jar:10.0.12]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933) ~[jetty-util-10.0.12.jar:10.0.12]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077) ~[jetty-util-10.0.12.jar:10.0.12]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by tresf** [comment]
Closed via #1133
