### ISSUE TITLE
javax.print.PrintException: PrintService is no longer available.

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1188]
Some PCs throw the following error when printing.  This may be caused by `PrintService` caching, which was added in #486 as part of some printer crawling/caching/performance improvements.

Steps to reproduce (unconfirmed)

-  User printed a few tickets successfully at 8:11.
-  User disconnected printer
-  Then at 11 :33 user reconnected printer and tried to print other tickets
-  User had the error
-  Printing with Qz Tray didn’t work anymore
-  User had to exit and relaunch Qz Tray and then it worked

... 

* As a bare minimum, we may need to force a recrawl of the printers when this occurs, to avoid a hard-failure.
* A permanent fix should better handle the loss of the `PrintService` pointer.

```
The message error is :

2023-10-04T11:34:42,722 [ERROR] Failed to print
javax.print.PrintException: PrintService is no longer available.
                at sun.print.Win32PrintJob.print(Unknown Source) ~[?:?]
                at qz.printer.action.PrintRaw.waitForPrint(PrintRaw.java:437) ~[qz-tray.jar:?]
                at qz.printer.action.PrintRaw.printToPrinter(PrintRaw.java:394) ~[qz-tray.jar:?]
                at qz.printer.action.PrintRaw.print(PrintRaw.java:339) ~[qz-tray.jar:?]
                at qz.utils.PrintingUtilities.processPrintRequest(PrintingUtilities.java:200) ~[qz-tray.jar:?]
                at qz.ws.PrintSocketClient.processMessage(PrintSocketClient.java:299) ~[qz-tray.jar:?]
                at qz.ws.PrintSocketClient.onMessage(PrintSocketClient.java:165) ~[qz-tray.jar:?]
                at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
                at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
                at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) ~[qz-tray.jar:?]
                at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68) ~[qz-tray.jar:?]
                at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.lambda$onTextFrame$1(JettyAnnotatedEventDriver.java:270) ~[qz-tray.jar:?]
                at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[qz-tray.jar:?]
                at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[qz-tray.jar:?]
                at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Vzor-** [comment]
I tested this on Windows 10 with a BOCA Lemur via USB.
I did the following procedure:

- Connected the printer and set it as default
- Started QZ tray
- Called 'find printer' on the exact printer name
- Printed a test, and confirmed it worked
- Disconnected the printer and waited
- Reconnected the printer and waited
- Printed a second test, and confirmed it worked

The logs are here https://gist.github.com/Vzor-/6e8da80a1d1ae9a57f552c68d1d22632
I was unable to reproduce the issue.

**Comment by tresf** [comment]
Me neither.  I'm not sure what causes this, but we'll need steps to reproduce to fix it.  Closing for now, please request a reopen with steps to reproduce.

**Comment by tresf** [comment]
Duplicate of #1259
