### ISSUE TITLE
Error initializing QuantumRenderer: no suitable pipeline found

### ISSUE THREAD

**Issue by tresf** [qzind/tray#122]
From an email thread.

> The issue is happening with jdk 8 with 32 processor. I have installed qz tray 2.0.1.
> Please let me know if anything else required.
> Sometimes i am getting this error, when i started using with Jdk version

```bash
> java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Server VM (build 25.101-b13, mixed mode)
```
```
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
    at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
    at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
    ... 1 more
Exception in thread "Thread-47" java.lang.RuntimeException: No toolkit found
    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:217)
    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
    at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
[TRACE] 2016-10-18 08:04:13,895 @ qz.printer.actio

java.lang.UnsupportedOperationException: Unable to start JavaFX service
    at qz.printer.action.PrintHTML.parseData(Unknown Source)
    at qz.ws.PrintSocketClient.processPrintRequest(Unknown Source)
    at qz.ws.PrintSocketClient.processMessage(Unknown Source)
    at qz.ws.PrintSocketClient.onMessage(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
    at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
    at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by klabarge** [comment]
I am unable to reproduce this error in either Windows 7 or Ubuntu 14.04

* **OS:** Ubuntu 14.04 32-bit and Windows 7 32-bit
 * **Note:** Both of these were VM's configured with Oracle Virtualbox 
* **Java:** 1.8.0_101
* **QZ Tray:** 2.0.1

These were the steps I had taken in attempt to reproduce the issue:

1. Installed the latest 32-bit version of Oracle Java 
 * **Ubuntu:** Via [adding the webupd8team/java repo](https://qz.io/wiki/upgrading-java#linux)
 * **Windows 7:** Downloaded [Java's offline installer](https://java.com/en/download/manual.jsp)
1. Installed latest version of QZ Tray at https://qz.io/download/
1. Successfully tested the print HTML feature at https://demo.qz.io

**Comment by tresf** [comment]
@klabarge thanks.  We'll close as invalid then.  👍
