### ISSUE TITLE
There is an incompatible JNA native library installed on this system

### ISSUE THREAD

**Issue by DreaserousProductions** [qzind/tray#1245]
```
Picked up _JAVA_OPTIONS: -Djna.nosys=true
Exception in thread "main" java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: TEMPLATE
Found:    4.0.0
(at C:\Users\Naghul\AppData\Local\Temp\jna--1969139829\jna10913920913462771444.dll).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:225)
	at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:83)
	at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42)
	at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:379)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:292)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:275)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:256)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:240)
	at javatap.score.main(score.java:38)
```

nothing seems to work, it was working fine but then all of a sudden this error popped up as i was updating some .dll files

**Comment by tresf** [comment]
* Which QZ Tray version? 
* What do you mean by "updating some DLLs"

**Comment by DreaserousProductions** [comment]
I got the problem solved. Thanks for the response.
