### ISSUE TITLE
com.sun.jna.platform.win32.Win32Exception: The system cannot find the file specified.

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1262]
The following can occur in very rare circumstances if the Startup folder is missing in Windows.

Cause:
* The folder `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup` is missing.

Workaround:

* Manually create the folder `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup`.

```
[ERROR] 2024-04-30T10:47:52,426 @ qz.App:86
	Could not start tray manager
java.lang.reflect.InvocationTargetException: null
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367) ~[?:?]
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342) ~[?:?]
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480) ~[?:?]
	at qz.ws.PrintSocketServer.runServer(PrintSocketServer.java:61) ~[production/:?]
	at qz.App.main(App.java:83) [production/:?]
Caused by: com.sun.jna.platform.win32.Win32Exception: The system cannot find the file specified.
	at com.sun.jna.platform.win32.Shell32Util.getKnownFolderPath(Shell32Util.java:93) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at qz.installer.WindowsSpecialFolders.getPath(WindowsSpecialFolders.java:90) ~[production/:?]
	at qz.installer.WindowsSpecialFolders.toString(WindowsSpecialFolders.java:95) ~[production/:?]
	at qz.installer.shortcut.WindowsShortcutCreator.canAutoStart(WindowsShortcutCreator.java:37) ~[production/:?]
	at qz.common.TrayManager.addMenuItems(TrayManager.java:357) ~[production/:?]
	at qz.common.TrayManager.<init>(TrayManager.java:206) ~[production/:?]
	at qz.ws.PrintSocketServer.lambda$runServer$0(PrintSocketServer.java:62) ~[production/:?]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
```

**Comment by tresf** [comment]
Closed via 6e0adba.
