### ISSUE TITLE
Connection closed: 1001 - null when using HID

### ISSUE THREAD

**Issue by tresf** [qzind/tray#128]
From our support tickets, after being left idle overnight, a user is experiencing problems getting the HID device to work.

A similar symptom was happening prior to 2bf75cb74acc436fa391251a3ff12273db18d23b when a page refresh happened mid-read however this is being tested against 2.0.2-RC2 which contains a patch to the race condition.

Possible causes:
 * USB power settings
 * Improper promise chaining
 * Upstream bug
 * ?

The reporting user will check power settings and let us know if they help.  We also require exact steps to reproduce for proper debugging.

The log below has additional `### Debug` messages added to help isolate the root of the problem.

```diff
  2016-11-08 07:58:09,910 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:09,926 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:09,942 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:09,957 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:09,973 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:09,988 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:10,004 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:10,020 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:10,035 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:10,051 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:10,067 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:10,082 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:10,098 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:10,113 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:10,129 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:10,145 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:10,160 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:10,176 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:10,191 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:10,207 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:10,223 [DEBUG] ### Reading HID data size: 6
  2016-11-08 07:58:10,238 [DEBUG] ### Successfully read response from device
  2016-11-08 07:58:10,254 [DEBUG] ### Reading HID data size: 6
- 2016-11-08 07:58:10,254 [INFO] Connection closed: 1001 - null
  2016-11-08 07:58:10,254 [INFO] Closing all communication channels for foo.bar
  2016-11-08 07:58:10,254 [INFO] ### Closing any/all serial ports
  2016-11-08 07:58:10,254 [INFO] ### Closing all open devices
  2016-11-08 07:58:10,254 [INFO] ### Closing vendor 2919
  2016-11-08 07:58:10,254 [INFO] ### Closing vendor 2919 device 21854
  2016-11-08 07:58:10,254 [DEBUG] ### Checking open status before closing...
  2016-11-08 07:58:10,254 [DEBUG] ### It's open... attempting to close...
  2016-11-08 07:58:10,254 [DEBUG] ### Leaving streaming mode alone, it's currently true
  2016-11-08 07:58:10,254 [DEBUG] ### Note, USB explicitly sets streaming to false on close whereas HID does not.
  2016-11-08 07:58:10,254 [INFO] ### Stopping listeners
  2016-11-08 07:58:10,254 [INFO] ### Skipping hidListener.close(), setting to null.
  2016-11-08 07:58:10,270 [DEBUG] ### Successfully read response from device
- 2016-11-08 07:58:10,270 [ERROR] Could not send message
- org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, outgoing connection not open
- at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:251)
-   at qz.ws.PrintSocketClient.send(Unknown Source)
-   at qz.ws.PrintSocketClient.sendStream(Unknown Source)
-   at qz.utils.UsbUtilities$1.run(Unknown Source)
  2016-11-08 08:00:43,755 [INFO] Connection opened from /0:0:0:0:0:0:0:1:64503 on socket port 8182
  2016-11-08 08:00:43,833 [DEBUG] Message: {"certificate":"<truncated>","promise":{},"timestamp":1478613643838,"uid":"2a9y2f"}
  2016-11-08 08:00:43,833 [DEBUG] Received new certificate from connection through 64503
  2016-11-08 08:00:43,833 [INFO] Allowed foo.bar to connect to QZ
  2016-11-08 08:00:44,005 [DEBUG] Message: {"call":"getVersion","promise":{},"signature":"<truncated>","timestamp":1478613643849,"uid":"ex9t7d"}
  2016-11-08 08:00:44,224 [DEBUG] Message: {"call":"websocket.getNetworkInfo","promise":{},"signature":"<truncated>","timestamp":1478613644032,"uid":"sbqn15"}
  2016-11-08 08:00:44,224 [INFO] Allowed foo.bar to access local resources
  2016-11-08 08:00:44,599 [DEBUG] Message: {"call":"hid.claimDevice","promise":{},"params":{"vendorId":"0b67","productId":"555e"},"signature":"<truncated>","timestamp":1478613644237,"uid":"j4zmfg"}
```

**Comment by klabarge** [comment]
I had a stream open between a Stamps.com scale and my Windows 10 computer. I enabled a power profile that would not allow sleeping, hibernating, or USB ports to go to sleep. I ran the sample.html page on a local webserver so there were no internet connectivity issues to demo.qz.io

1. After 6 hours I attempted to add/remove weight from the scale.  The value appearing on the webpage (sample.html) did not change.

2. Next, I tried to "List Devices", which took about 20 seconds to execute.  My HID device did list, but the Manufacturer and Product fields were `undefined`

  ![image](https://cloud.githubusercontent.com/assets/12505463/20196114/4157753c-a767-11e6-9cfa-27bb67a4cf4e.png)

3. I released the device, which seemed to work.

4. I tried to claim the device,  and after about 15 seconds I received the error "Error: Failed to open connection to device".  However, I tried to claim the device again, and I got "Error: USB Device [v:0x1446 p:0x6a73] is already claimed."

5. I then tried "Open Stream", but it was stuck at "Waiting on device" (I waited over 2 minutes before hitting Close Stream, which seemed to be "successful").

6. I then unplugged my scale (which shuts it off) and I received the below Windows error message.  QZ Tray quit.

   ![image](https://cloud.githubusercontent.com/assets/12505463/20196667/b78c5996-a769-11e6-97da-d7ecdcc1474b.png)

7. I re-launched QZ Tray and everything worked normally.

Unfortunately I did not have the software running from the console, so I was potentially missing helpful logs.  I'll attempt to reproduce to provide more logs.

**Comment by tresf** [comment]
Not yet able to reproduce... 

I have an instance of `2.0.2` that has been running stable and responsive on Windows 7 32-bit for 20 hours.

![screen shot 2016-11-11 at 6 07 35 pm](https://cloud.githubusercontent.com/assets/6345473/20232928/c10e2c1c-a839-11e6-937a-28d12e53fa39.png)

**Comment by tresf** [comment]
So by combining HTML, PDF and USB I was quickly able to produce an `OutOfMemory` error.  I'm not sure if this is related or a separate bug.  Backtrace here:

https://gist.github.com/tresf/da198dfcbad8c8ab28f761669e820afd

**Comment by tresf** [comment]
Client reports the issue is caused by two HID connections from separate web pages (e.g. forward/back buttons).  Client is preparing a `sample.html` which will reproduce problem.

**Comment by klabarge** [comment]
> I'll attempt to reproduce to provide more logs.

I launched the software via the console and was able to reproduce the error (except for the crash when unplugging the scale).  Unfortunately, the logs provided absolutely no information.  No indication of a crash or even errors; the logs indicated that QZ Tray was running fine.

Perhaps there is something strange happening with my scale?

**Comment by tresf** [comment]
For the Windows builds, we will most likely switch to `purejavahidapi` library in 2.0.3 as the testing has shows better stability than the `garry-rowe` version we have bundled in 2.0.2.

To test this build out now for Windows:  https://github.com/tresf/tray/releases/download/v2.0.2-ALT/qz-tray-2.0.2-alt.exe

For the Mac builds, we are escalating the issue in #137, which seems to be a [race condition/threading problem with MacOS](https://github.com/signal11/hidapi/issues/205#issuecomment-70159844).

**Comment by tresf** [comment]
I'm closing this as upstream for now since it's not reliably reproducible and was predominantly fixed with a proper Promise chain combined with a new HID library which we're testing against for 2.0.3.
