### ISSUE TITLE
Logs spammed with ClosedChannelException

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1300]
A client has logs files with these messages spammed hundreds of times.

I believe this is a sign that the websocket has closed, but the listener for USB has not.

```
2024-10-25T13:04:50,416 [ERROR] Could not send message
java.io.IOException: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.util.FutureCallback.block(FutureCallback.java:163) ~[qz-tray.jar:?]
	at org.eclipse.jetty.util.FutureCallback.block(FutureCallback.java:139) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.JettyWebSocketRemoteEndpoint.sendBlocking(JettyWebSocketRemoteEndpoint.java:191) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.JettyWebSocketRemoteEndpoint.sendString(JettyWebSocketRemoteEndpoint.java:52) ~[qz-tray.jar:?]
	at qz.ws.PrintSocketClient.send(PrintSocketClient.java:803) [qz-tray.jar:?]
	at qz.ws.PrintSocketClient.sendStream(PrintSocketClient.java:788) [qz-tray.jar:?]
	at qz.utils.UsbUtilities$1.run(UsbUtilities.java:209) [qz-tray.jar:?]
Caused by: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onOutgoingFrame(WebSocketSessionState.java:184) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.sendFrame(WebSocketCoreSession.java:514) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.JettyWebSocketRemoteEndpoint.sendBlocking(JettyWebSocketRemoteEndpoint.java:190) ~[qz-tray.jar:?]
	... 4 more
```

**Comment by tresf** [comment]
Closed via #1304
