### ISSUE TITLE
Double call to setSignatureAlgorithm can cause uncaught exception

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1301]
The exception is:

```
qz-tray.js:772 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.versionCompare (qz-tray.js:772:31)
    at Object.isVersion (qz-tray.js:790:34)
    at Object.algorithm (qz-tray.js:974:35)
    at Object.setSignatureAlgorithm (qz-tray.js:2713:37)
    at myFunc (sample.html:107:25)
    at sample.html:137:9
```

The code to reproduce is:

```js
        function myFunc(attempt) {
            console.log("Attempt:", attempt);
            qz.security.setSignatureAlgorithm("SHA512"); // Since 2.1

            if (!qz.websocket.isActive()) {
                var config = [];
                qz.websocket.connect(config)
                .then(() => console.log("Success!!!"))
                .catch((err) => console.error(err));
            }
        }

        myFunc(1);
        myFunc(2);
```

**Comment by tresf** [comment]
This will be fixed with qz-tray.js@2.2.5.  In the meantime, please use a snapshot here: https://github.com/qzind/tray/blob/master/js/qz-tray.js
