### ISSUE TITLE
Error loading prefs.properties file Ubuntu 16.04

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#132]
**OS:** Ubuntu 16.04
**Java:** Oracle 8u111
**QZ Tray:** 2.0.2

When starting QZ Tray, an error `Error loading /home/kyle/.qz/prefs.properties` is thrown.  The software still launches, and at least basic functionality seems fine.  I successfully searched for printers.

```
kyle@lagunitas:~$ java -Xms512m -jar /opt/qz-tray/qz-tray.jar
Nov 13, 2016 10:17:04 PM qz.common.PropertyHelper load
SEVERE: Error loading /home/kyle/.qz/prefs.properties
java.io.FileNotFoundException: /home/kyle/.qz/prefs.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at qz.common.PropertyHelper.load(Unknown Source)
	at qz.common.PropertyHelper.<init>(Unknown Source)
	at qz.common.TrayManager.<init>(Unknown Source)
	at qz.ws.PrintSocketServer$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

[DEBUG] 2016-11-13 22:17:04,911 @ qz.utils.ShellUtilities:?
	Executing: [uname, -a]
[DEBUG] 2016-11-13 22:17:04,931 @ qz.utils.ShellUtilities:?
	Executing: [gconftool-2, --get, /desktop/gnome/shell/windows/theme]
[DEBUG] 2016-11-13 22:17:04,948 @ qz.utils.ShellUtilities:?
	Executing: [grep, dark_bg_color, /usr/share/themes/Ambiance/gtk-3.0/gtk.css]
[DEBUG] 2016-11-13 22:17:04,951 @ qz.utils.ShellUtilities:?
	Executing: [grep, dark_bg_color, /usr/share/themes/Ambiance/gtk-3.0/gtk-main.css]
[INFO] 2016-11-13 22:17:04,963 @ qz.deploy.DeployUtilities:?
	Main properties file /opt/qz-tray/qz-tray.properties
[DEBUG] 2016-11-13 22:17:04,963 @ qz.utils.ShellUtilities:?
	Executing: [certutil, -d, sql:/home/kyle/.pki/nssdb, -A, -t, TC, -n, QZ Industries, LLC, -i, /opt/qz-tray/auth/qz-tray.crt]
[WARN] 2016-11-13 22:17:04,973 @ qz.deploy.LinuxCertificate:?
	Error executing certutil.  Ensure it is installed properly with write access to sql:/home/kyle/.pki/nssdb. Secure websockets will not function on certain browsers.
[INFO] 2016-11-13 22:17:05,249 @ qz.deploy.DeployUtilities:?
	Main properties file /opt/qz-tray/qz-tray.properties
[DEBUG] 2016-11-13 22:17:05,336 @ qz.auth.Certificate:?
	Using trusted root certificate: CN=qzindustries.com, O=QZ Industries, LLC (8ef2c0b2fe3f75754245b3fb9d54c0caa1b46bb3)
[INFO] 2016-11-13 22:17:05,346 @ qz.auth.CRL:?
	Loading CRL from https://crl.qz.io
[DEBUG] 2016-11-13 22:17:05,950 @ qz.ws.SingleInstanceChecker:?
	Checking for a running instance of QZ Tray on port 8283
[DEBUG] 2016-11-13 22:17:06,034 @ qz.ws.SingleInstanceChecker:?
	Checking for a running instance of QZ Tray on port 8384
[DEBUG] 2016-11-13 22:17:06,042 @ qz.ws.SingleInstanceChecker:?
	Checking for a running instance of QZ Tray on port 8485
[INFO] 2016-11-13 22:17:06,065 @ qz.ws.PrintSocketServer:?
	Server started on port(s) 8182, 8181
[INFO] 2016-11-13 22:17:06,506 @ qz.auth.CRL:?
	Successfully loaded 1 CRL entries from https://crl.qz.io
```

**Comment by tresf** [comment]
This was made visible by #130 but was actually there all along.  QZ Tray creates the preferences file if it doesn't exist, but on first launch it wasn't there and threw this error.  Since a fresh install launches it without the console visible, this was being thrown on every fresh install we just never knew.

I've reduced the severity from SEVERE to WARNING, which should be more appeasing.
