### ISSUE TITLE
USB device not released properly

### ISSUE THREAD

**Issue by tresf** [qzind/tray#21]
Quoted from an email, needs confirmation.

***

```
C:\Program Files\QZ Tray>java -jar qz-tray.jar
[DEBUG] 2016-03-31 10:45:19,770 @ qz.utils.ShellUtilities:?
        Executing: [C:\WINDOWS\system32\reg.exe, query, HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1, /v, Flags]
[DEBUG] 2016-03-31 10:45:19,772 @ qz.utils.ShellUtilities:?
        Executing: [C:\WINDOWS\system32\reg.exe, query, HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\micr
osoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\ExperimentalFeatures, /v, AllowLocalhostLoopback]
[DEBUG] 2016-03-31 10:45:19,919 @ qz.auth.Certificate:?
        Using trusted root certificate: CN=qzindustries.com, O=QZ Industries, LLC (8ef2c0b2fe3f75754245b3fb9d54c0caa1b46bb3)
[INFO] 2016-03-31 10:45:19,919 @ qz.auth.CRL:?
        Loading CRL from https://crl.qz.io
[DEBUG] 2016-03-31 10:45:19,988 @ qz.utils.ShellUtilities:?
        Executing: [C:\WINDOWS\system32\reg.exe, query, HKCU\Software\Microsoft\Windows\CurrentVersion\Run\, /v, QZ Tray]
[INFO] 2016-03-31 10:45:20,003 @ qz.deploy.DeployUtilities:?
        SSL properties file from C:\Program Files\QZ Tray\qz-tray.properties
[DEBUG] 2016-03-31 10:45:20,126 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8283
[DEBUG] 2016-03-31 10:45:20,171 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8384
[DEBUG] 2016-03-31 10:45:20,172 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8485
[INFO] 2016-03-31 10:45:20,172 @ qz.ws.PrintSocketServer:?
        Server started on port(s) 8182, 8181
[INFO] 2016-03-31 10:45:20,404 @ qz.auth.CRL:?
        Successfully loaded 1 CRL entries from https://crl.qz.io
[INFO] 2016-03-31 10:45:33,077 @ qz.ws.PrintSocketClient:?
        Connection opened from /0:0:0:0:0:0:0:1:58015 on socket port 8182
[DEBUG] 2016-03-31 10:45:33,084 @ qz.ws.PrintSocketClient:?
        Message: {"certificate":"-----BEGIN CERTIFICATE-----<snip>-----END CERTIFICATE-----\n","promise":{},"timestamp":1459442733075,"uid":"4llsb6"}
[DEBUG] 2016-03-31 10:45:33,095 @ qz.ws.PrintSocketClient:?
        Received new certificate from connection through 58015
[INFO] 2016-03-31 10:45:33,095 @ qz.common.TrayManager:?
        Allowed localhost to connect to QZ
[DEBUG] 2016-03-31 10:45:33,105 @ qz.ws.PrintSocketClient:?
        Message: {"call":"getVersion","promise":{},"timestamp":1459442733101,"uid":"0nhq60"}
[WARN] 2016-03-31 10:45:33,106 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[DEBUG] 2016-03-31 10:45:38,277 @ qz.ws.PrintSocketClient:?
        Message: {"call":"usb.listDevices","promise":{},"params":{"includeHubs":true},"timestamp":1459442738274,"uid":"op6loy"}
[WARN] 2016-03-31 10:45:38,277 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[INFO] 2016-03-31 10:45:39,746 @ qz.common.TrayManager:?
        Allowed localhost to access USB devices
[DEBUG] 2016-03-31 10:45:44,606 @ qz.ws.PrintSocketClient:?
        Message: {"call":"usb.listInterfaces","promise":{},"params":{"vendorId":"0x0922","productId":"0x8004"},"timestamp":1459442744604,"uid":"jd4cll"}
[WARN] 2016-03-31 10:45:44,606 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[INFO] 2016-03-31 10:45:46,621 @ qz.common.TrayManager:?
        Allowed localhost to access USB devices
[DEBUG] 2016-03-31 10:46:11,527 @ qz.ws.PrintSocketClient:?
        Message: {"call":"usb.listInterfaces","promise":{},"params":{"vendorId":"0x0922","productId":"0x8004"},"timestamp":1459442771526,"uid":"m68kik"}
[WARN] 2016-03-31 10:46:11,527 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[INFO] 2016-03-31 10:46:13,247 @ qz.common.TrayManager:?
        Allowed localhost to access USB devices
[DEBUG] 2016-03-31 10:46:16,961 @ qz.ws.PrintSocketClient:?
        Message: {"call":"usb.listEndpoints","promise":{},"params":{"vendorId":"0x0922","productId":"0x8004","interface":"0x00"},"timestamp":1459442776960,"uid"
:"2jx3sx"}
[WARN] 2016-03-31 10:46:16,962 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[INFO] 2016-03-31 10:46:18,320 @ qz.common.TrayManager:?
        Allowed localhost to access USB devices
[DEBUG] 2016-03-31 10:46:26,615 @ qz.ws.PrintSocketClient:?
        Message: {"call":"usb.claimDevice","promise":{},"params":{"vendorId":"0x0922","productId":"0x8004","interface":"0x00"},"timestamp":1459442786614,"uid":"
0oko8u"}
[WARN] 2016-03-31 10:46:26,616 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[INFO] 2016-03-31 10:46:28,430 @ qz.common.TrayManager:?
        Allowed localhost to claim a USB device
[DEBUG] 2016-03-31 10:46:34,869 @ qz.ws.PrintSocketClient:?
        Message: {"call":"usb.openStream","promise":{},"params":{"vendorId":"0x0922","productId":"0x8004","endpoint":"0x82","responseSize":"8","interval":"10"},
"timestamp":1459442794869,"uid":"a5opx8"}
[WARN] 2016-03-31 10:46:34,869 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[INFO] 2016-03-31 10:46:38,083 @ qz.common.TrayManager:?
        Allowed localhost to use a USB device
[DEBUG] 2016-03-31 10:46:41,365 @ qz.ws.PrintSocketClient:?
        Message: {"call":"usb.releaseDevice","promise":{},"params":{"vendorId":"0x0922","productId":"0x8004"},"timestamp":1459442801365,"uid":"4e8rni"}
[WARN] 2016-03-31 10:46:41,366 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[INFO] 2016-03-31 10:46:42,910 @ qz.common.TrayManager:?
        Allowed localhost to release a USB device
[ERROR] 2016-03-31 10:46:42,925 @ qz.ws.PrintSocketClient:?
        Problem processing message
javax.usb.UsbPlatformException: USB error 5: Unable to release interface: Entity not found
        at org.usb4java.javax.ExceptionUtils.createPlatformException(ExceptionUtils.java:39)
        at org.usb4java.javax.AbstractDevice.releaseInterface(AbstractDevice.java:455)
        at org.usb4java.javax.Interface.release(Interface.java:113)
        at qz.communication.UsbIO.close(Unknown Source)
        at qz.ws.PrintSocketClient.processMessage(Unknown Source)
        at qz.ws.PrintSocketClient.onMessage(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
```

That's where the first error shows up.  I see that it allowed localhost to release the USB device in the log but it also throws an error.

Then if I try to reclaim the device I get
```
[DEBUG] 2016-03-31 10:49:27,000 @ qz.ws.PrintSocketClient:?
        Message: {"call":"usb.claimDevice","promise":{},"params":{"vendorId":"0x0922","productId":"0x8004","interface":"0x00"},"timestamp":1459442967000,"uid":"
w7rrds"}
[WARN] 2016-03-31 10:49:27,001 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[INFO] 2016-03-31 10:49:28,711 @ qz.common.TrayManager:?
        Allowed localhost to claim a USB device
```

which looks like it allows the claim to go through, but in the browser it throws the error message of

```
Error: USB Device [v:0x0922 p:0x8004] is already claimed.
```

**Comment by tresf** [comment]
Closed via 0d1e275
