### ISSUE TITLE
Serial port returning null about 50% of the time

### ISSUE THREAD

**Issue by tresf** [qzind/tray#23]
Setting | Value
----------|--------
Baud | `9600`
Data Bits | `7`
Stop Bits | `1`
Parity | `EVEN`
Flow Control | `NONE`
Command | `W\n`
STX | `0x02`
ETX | `0x0D`

**Hardware:**  MT P90 Scale with USB-to-Serial adapter.

**1.9 Attempts:**
 * 000.000
 * 000.000
 * 000.000
 * 000.000
 * 000.000
 * 000.000
 * 000.000
 * 000.000
 * 000.000
 * 000.000

**2.0 attempts:**
 * null
 * 000.000
 * null
 * null
 * null
 * null
 * 000.000
 * 000.000
 * 000.000
 * null

**Comment by bberenz** [comment]
Can you provide logs? And how are you running these attempts?

**Comment by tresf** [comment]
> Can you provide logs?

Sure, but they'll just show the response being null half of the time.

> And how are you running these attempts?

Directly through sample.html, so nothing out of the standard MT Scale testing.

**Comment by tresf** [comment]
```
[DEBUG] 2016-04-08 22:58:17,518 @ qz.auth.Certificate:124
	Using trusted root certificate: CN=qzindustries.com, O=QZ Industries, LLC (8ef2c0b2fe3f75754245b3fb9d54c0caa1b46bb3)
[INFO] 2016-04-08 22:58:17,518 @ qz.auth.CRL:38
	Loading CRL from https://crl.qz.io
[INFO] 2016-04-08 22:58:17,930 @ qz.deploy.DeployUtilities:339
	SSL properties file from C:\Users\Tres\Desktop\tray\out\qz-tray.properties
java.io.FileNotFoundException: C:\Users\Tres\Desktop\tray\out\qz-tray.properties (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at qz.deploy.DeployUtilities.loadSSLProperties(DeployUtilities.java:342)
	at qz.ws.PrintSocketServer.runServer(PrintSocketServer.java:109)
	at qz.ws.PrintSocketServer.main(PrintSocketServer.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
[WARN] 2016-04-08 22:58:17,934 @ qz.deploy.DeployUtilities:348
	Failed to load properties file!
[DEBUG] 2016-04-08 22:58:17,972 @ qz.utils.ShellUtilities:104
	Executing: [C:\WINDOWS\system32\reg.exe, query, HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1, /v, Flags]
[DEBUG] 2016-04-08 22:58:18,047 @ qz.utils.ShellUtilities:104
	Executing: [C:\WINDOWS\system32\reg.exe, query, HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\ExperimentalFeatures, /v, AllowLocalhostLoopback]
[WARN] 2016-04-08 22:58:18,133 @ qz.ws.PrintSocketServer:128
	Could not start secure WebSocket
[DEBUG] 2016-04-08 22:58:18,133 @ qz.utils.ShellUtilities:65
	Executing: [C:\WINDOWS\system32\reg.exe, query, HKCU\Software\Microsoft\Windows\CurrentVersion\Run\, /v, QZ Tray]
[DEBUG] 2016-04-08 22:58:18,547 @ qz.ws.SingleInstanceChecker:44
	Checking for a running instance of QZ Tray on port 8283
[DEBUG] 2016-04-08 22:58:18,723 @ qz.ws.SingleInstanceChecker:44
	Checking for a running instance of QZ Tray on port 8384
[DEBUG] 2016-04-08 22:58:18,750 @ qz.ws.SingleInstanceChecker:44
	Checking for a running instance of QZ Tray on port 8485
[INFO] 2016-04-08 22:58:18,880 @ qz.ws.PrintSocketServer:145
	Server started on port(s) 8182
[INFO] 2016-04-08 22:58:19,948 @ qz.auth.CRL:51
	Successfully loaded 1 CRL entries from https://crl.qz.io
[INFO] 2016-04-08 22:58:44,719 @ qz.ws.PrintSocketClient:119
	Connection opened from /0:0:0:0:0:0:0:1:49505 on socket port 8182
[DEBUG] 2016-04-08 22:58:44,733 @ qz.ws.PrintSocketClient:166
	Message: {"certificate":"-----BEGIN CERTIFICATE-----\nMIIFAzCCAuugAwIBAgICEAIwDQYJKoZIhvcNAQEFBQAwgZgxCzAJBgNVBAYTAlVT\nMQswCQYDVQQIDAJOWTEbMBkGA1UECgwSUVogSW5kdXN0cmllcywgTExDMRswGQYD\nVQQLDBJRWiBJbmR1c3RyaWVzLCBMTEMxGTAXBgNVBAMMEHF6aW5kdXN0cmllcy5j\nb20xJzAlBgkqhkiG9w0BCQEWGHN1cHBvcnRAcXppbmR1c3RyaWVzLmNvbTAeFw0x\nNTAzMTkwMjM4NDVaFw0yNTAzMTkwMjM4NDVaMHMxCzAJBgNVBAYTAkFBMRMwEQYD\nVQQIDApTb21lIFN0YXRlMQ0wCwYDVQQKDAREZW1vMQ0wCwYDVQQLDAREZW1vMRIw\nEAYDVQQDDAlsb2NhbGhvc3QxHTAbBgkqhkiG9w0BCQEWDnJvb3RAbG9jYWxob3N0\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtFzbBDRTDHHmlSVQLqjY\naoGax7ql3XgRGdhZlNEJPZDs5482ty34J4sI2ZK2yC8YkZ/x+WCSveUgDQIVJ8oK\nD4jtAPxqHnfSr9RAbvB1GQoiYLxhfxEp/+zfB9dBKDTRZR2nJm/mMsavY2DnSzLp\nt7PJOjt3BdtISRtGMRsWmRHRfy882msBxsYug22odnT1OdaJQ54bWJT5iJnceBV2\n1oOqWSg5hU1MupZRxxHbzI61EpTLlxXJQ7YNSwwiDzjaxGrufxc4eZnzGQ1A8h1u\njTaG84S1MWvG7BfcPLW+sya+PkrQWMOCIgXrQnAsUgqQrgxQ8Ocq3G4X9UvBy5VR\nCwIDAQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG+EIBDQQfFh1PcGVuU1NMIEdl\nbmVyYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUpG420UhvfwAFMr+8vf3pJunQ\ngH4wHwYDVR0jBBgwFoAUkKZQt4TUuepf8gWEE3hF6Kl1VFwwDQYJKoZIhvcNAQEF\nBQADggIBAFXr6G1g7yYVHg6uGfh1nK2jhpKBAOA+OtZQLNHYlBgoAuRRNWdE9/v4\nJ/3Jeid2DAyihm2j92qsQJXkyxBgdTLG+ncILlRElXvG7IrOh3tq/TttdzLcMjaR\n8w/AkVDLNL0z35shNXih2F9JlbNRGqbVhC7qZl+V1BITfx6mGc4ayke7C9Hm57X0\nak/NerAC/QXNs/bF17b+zsUt2ja5NVS8dDSC4JAkM1dD64Y26leYbPybB+FgOxFu\nwou9gFxzwbdGLCGboi0lNLjEysHJBi90KjPUETbzMmoilHNJXw7egIo8yS5eq8RH\ni2lS0GsQjYFMvplNVMATDXUPm9MKpCbZ7IlJ5eekhWqvErddcHbzCuUBkDZ7wX/j\nunk/3DyXdTsSGuZk3/fLEsc4/YTujpAjVXiA1LCooQJ7SmNOpUa66TPz9O7Ufkng\n+CoTSACmnlHdP7U9WLr5TYnmL9eoHwtb0hwENe1oFC5zClJoSX/7DRexSJfB7YBf\nvn6JA2xy4C6PqximyCPisErNp85GUcZfo33Np1aywFv9H+a83rSUcV6kpE/jAZio\n5qLpgIOisArj1HTM6goDWzKhLiR/AeG3IJvgbpr9Gr7uZmfFyQzUjvkJ9cybZRd+\nG8azmpBBotmKsbtbAU/I/LVk8saeXznshOVVpDRYtVnjZeAneso7\n-----END CERTIFICATE-----\n--START INTERMEDIATE CERT--\n-----BEGIN CERTIFICATE-----\nMIIFEjCCA/qgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwgawxCzAJBgNVBAYTAlVT\nMQswCQYDVQQIDAJOWTESMBAGA1UEBwwJQ2FuYXN0b3RhMRswGQYDVQQKDBJRWiBJ\nbmR1c3RyaWVzLCBMTEMxGzAZBgNVBAsMElFaIEluZHVzdHJpZXMsIExMQzEZMBcG\nA1UEAwwQcXppbmR1c3RyaWVzLmNvbTEnMCUGCSqGSIb3DQEJARYYc3VwcG9ydEBx\nemluZHVzdHJpZXMuY29tMB4XDTE1MDMwMjAwNTAxOFoXDTM1MDMwMjAwNTAxOFow\ngZgxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJOWTEbMBkGA1UECgwSUVogSW5kdXN0\ncmllcywgTExDMRswGQYDVQQLDBJRWiBJbmR1c3RyaWVzLCBMTEMxGTAXBgNVBAMM\nEHF6aW5kdXN0cmllcy5jb20xJzAlBgkqhkiG9w0BCQEWGHN1cHBvcnRAcXppbmR1\nc3RyaWVzLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANTDgNLU\niohl/rQoZ2bTMHVEk1mA020LYhgfWjO0+GsLlbg5SvWVFWkv4ZgffuVRXLHrwz1H\nYpMyo+Zh8ksJF9ssJWCwQGO5ciM6dmoryyB0VZHGY1blewdMuxieXP7Kr6XD3GRM\nGAhEwTxjUzI3ksuRunX4IcnRXKYkg5pjs4nLEhXtIZWDLiXPUsyUAEq1U1qdL1AH\nEtdK/L3zLATnhPB6ZiM+HzNG4aAPynSA38fpeeZ4R0tINMpFThwNgGUsxYKsP9kh\n0gxGl8YHL6ZzC7BC8FXIB/0Wteng0+XLAVto56Pyxt7BdxtNVuVNNXgkCi9tMqVX\nxOk3oIvODDt0UoQUZ/umUuoMuOLekYUpZVk4utCqXXlB4mVfS5/zWB6nVxFX8Io1\n9FOiDLTwZVtBmzmeikzb6o1QLp9F2TAvlf8+DIGDOo0DpPQUtOUyLPCh5hBaDGFE\nZhE56qPCBiQIc4T2klWX/80C5NZnd/tJNxjyUyk7bjdDzhzT10CGRAsqxAnsjvMD\n2KcMf3oXN4PNgyfpbfq2ipxJ1u777Gpbzyf0xoKwH9FYigmqfRH2N2pEdiYawKrX\n6pyXzGM4cvQ5X1Yxf2x/+xdTLdVaLnZgwrdqwFYmDejGAldXlYDl3jbBHVM1v+uY\n5ItGTjk+3vLrxmvGy5XFVG+8fF/xaVfo5TW5AgMBAAGjUDBOMB0GA1UdDgQWBBSQ\nplC3hNS56l/yBYQTeEXoqXVUXDAfBgNVHSMEGDAWgBQDRcZNwPqOqQvagw9BpW0S\nBkOpXjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAJIO8SiNr9jpLQ\neUsFUmbueoxyI5L+P5eV92ceVOJ2tAlBA13vzF1NWlpSlrMmQcVUE/K4D01qtr0k\ngDs6LUHvj2XXLpyEogitbBgipkQpwCTJVfC9bWYBwEotC7Y8mVjjEV7uXAT71GKT\nx8XlB9maf+BTZGgyoulA5pTYJ++7s/xX9gzSWCa+eXGcjguBtYYXaAjjAqFGRAvu\npz1yrDWcA6H94HeErJKUXBakS0Jm/V33JDuVXY+aZ8EQi2kV82aZbNdXll/R6iGw\n2ur4rDErnHsiphBgZB71C5FD4cdfSONTsYxmPmyUb5T+KLUouxZ9B0Wh28ucc1Lp\nrbO7BnjW\n-----END CERTIFICATE-----\n","promise":{},"timestamp":1460170724718,"uid":"xxhcbu"}
[DEBUG] 2016-04-08 22:58:44,755 @ qz.ws.PrintSocketClient:180
	Received new certificate from connection through 49505
[INFO] 2016-04-08 22:58:46,150 @ qz.common.TrayManager:413
	Allowed localhost to connect to QZ
[DEBUG] 2016-04-08 22:58:46,193 @ qz.ws.PrintSocketClient:166
	Message: {"call":"getVersion","promise":{},"timestamp":1460170726173,"uid":"nqu4e7"}
[WARN] 2016-04-08 22:58:46,195 @ qz.ws.PrintSocketClient:204
	Bad signature on request
[DEBUG] 2016-04-08 22:59:08,094 @ qz.ws.PrintSocketClient:166
	Message: {"call":"serial.openPort","promise":{},"params":{"port":"COM4","bounds":{"begin":"0x0002","end":"0x000D","width":null}},"timestamp":1460170748086,"uid":"03zea3"}
[WARN] 2016-04-08 22:59:08,095 @ qz.ws.PrintSocketClient:204
	Bad signature on request
[INFO] 2016-04-08 22:59:09,388 @ qz.common.TrayManager:413
	Allowed localhost to open a serial port
[DEBUG] 2016-04-08 22:59:16,611 @ qz.ws.PrintSocketClient:166
	Message: {"call":"serial.sendData","promise":{},"params":{"port":"COM4","data":"W\\n","properties":{"baudRate":"9600","dataBits":"7","stopBits":"1","parity":"EVEN","flowControl":"NONE"}},"timestamp":1460170756606,"uid":"2i5xgw"}
[WARN] 2016-04-08 22:59:16,612 @ qz.ws.PrintSocketClient:204
	Bad signature on request
[INFO] 2016-04-08 22:59:19,432 @ qz.common.TrayManager:413
	Allowed localhost to send data over a serial port
[TRACE] 2016-04-08 22:59:19,459 @ qz.utils.SerialUtilities:271
	Parsed serial setting: BAUDRATE_9600
[TRACE] 2016-04-08 22:59:19,460 @ qz.utils.SerialUtilities:148
	Parsed serial setting: DATABITS_7
[TRACE] 2016-04-08 22:59:19,460 @ qz.utils.SerialUtilities:171
	Parsed serial setting: STOPBITS_1
[TRACE] 2016-04-08 22:59:19,460 @ qz.utils.SerialUtilities:240
	Parsed serial setting: PARITY_EVEN
[TRACE] 2016-04-08 22:59:19,461 @ qz.utils.SerialUtilities:199
	Parsed serial setting: FLOWCONTROL_NONE
[DEBUG] 2016-04-08 22:59:19,464 @ qz.communication.SerialIO:135
	Sending data over [COM4]
[DEBUG] 2016-04-08 22:59:19,604 @ qz.ws.PrintSocketClient:484
	Received serial output: 000.90
[DEBUG] 2016-04-08 22:59:21,804 @ qz.ws.PrintSocketClient:166
	Message: {"call":"serial.sendData","promise":{},"params":{"port":"COM4","data":"W\\n","properties":{"baudRate":"9600","dataBits":"7","stopBits":"1","parity":"EVEN","flowControl":"NONE"}},"timestamp":1460170761797,"uid":"rla1y2"}
[WARN] 2016-04-08 22:59:21,805 @ qz.ws.PrintSocketClient:204
	Bad signature on request
[INFO] 2016-04-08 22:59:22,807 @ qz.common.TrayManager:413
	Allowed localhost to send data over a serial port
[TRACE] 2016-04-08 22:59:22,808 @ qz.utils.SerialUtilities:271
	Parsed serial setting: BAUDRATE_9600
[TRACE] 2016-04-08 22:59:22,809 @ qz.utils.SerialUtilities:148
	Parsed serial setting: DATABITS_7
[TRACE] 2016-04-08 22:59:22,811 @ qz.utils.SerialUtilities:171
	Parsed serial setting: STOPBITS_1
[TRACE] 2016-04-08 22:59:22,811 @ qz.utils.SerialUtilities:240
	Parsed serial setting: PARITY_EVEN
[TRACE] 2016-04-08 22:59:22,811 @ qz.utils.SerialUtilities:199
	Parsed serial setting: FLOWCONTROL_NONE
[DEBUG] 2016-04-08 22:59:22,823 @ qz.communication.SerialIO:135
	Sending data over [COM4]
[DEBUG] 2016-04-08 22:59:22,905 @ qz.ws.PrintSocketClient:484
	Received serial output: null
[DEBUG] 2016-04-08 22:59:22,920 @ qz.ws.PrintSocketClient:484
	Received serial output: null
```

**Comment by bberenz** [comment]
When I rewrote the serial classes I wasn't aware messages could be split over multiple receives.
315a17c8b88e96f5d47fe4bdf1bd09885b17314a fixes that with a byte buffer that will return complete messages as it receives them.

**Comment by tresf** [comment]
Tested, works.
