### ISSUE TITLE
HID + websocket errors in Windows 10 "Remote Endpoint unavailable"

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#258]
**OS:** Windows 10
**QZ Tray:** Reproducible in 2.0.3 +

When an HID device is power cycled with an Open Stream, the websocket connection must be re-established (e.g. page refresh) for the software to read values from the HID device (scale).

Once the page is refreshed, `RemoteEndpoint unavailable` errors are spammed to the logs indefinitely until QZ Tray restarted. Other than log spamming, the software appears to be functioning properly. 

```
[ERROR] 2017-11-28 01:21:54,937 @ qz.ws.PrintSocketClient:?
        Could not send message
org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, outgoing connection not open
        at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:251)
        at qz.ws.PrintSocketClient.send(Unknown Source)
        at qz.ws.PrintSocketClient.sendStream(Unknown Source)
        at qz.utils.UsbUtilities$1.run(Unknown Source)
```

**Steps to Reproduce:**

1. Connect a USB scale to a Windows 10 computer
1. Open sample.html, claim the device and open a stream
1. Power cycle the USB scale
1. Refresh the sample.html page
1. Check logs and verify that `RemoteEndpoint unavailable` errors are spammed to the logs

**Comment by bberenz** [comment]
I've changed the connection manager to explicitly turn off streaming when closing and I've changed the streaming methods to catch the websocket exception, so if this does still occur there will only be one stacktrace and the device will quit trying to stream.

At least, it _should_, unfortunately the scale I used to use to test this is broken, so I cannot confirm this fix first hand at the moment. If you can confirm 49a11fd3343eaa83c1d34d2bbb2400af055ed116 handles this properly.

> the websocket connection must be re-established (e.g. page refresh) for the software to read values from the HID device 

In regards to this, I'm pretty sure you can just unclaim/re-claim the device to resume reading values (you'll have to open another stream though) without refreshing the page. I know the (now broken) scale I used powered itself off all the time when we were adding hid and unless I'm mistaken that was all I had to do, been a while though.

**Comment by klabarge** [comment]
> If you can confirm 49a11fd handles this properly.

Yes, this fixed work. The error was only thrown once.

> In regards to this, I'm pretty sure you can just unclaim/re-claim the device to resume reading values

So this is the behavior in macOS. Releasing and then re-claiming, and then opening a new stream allows you to resume reading values from the scale.

In Windows, I am unable to release the device after it has been power cycled. A "device not open" error is thrown:

```
[ERROR] 2017-11-28 18:10:20,736 @ qz.ws.PrintSocketClient:?
        Problem processing message
java.lang.IllegalStateException: device not open
        at purejavahidapi.HidDevice.setInputReportListener(HidDevice.java:76)
        at qz.communication.PJHA_HidIO.close(Unknown Source)
        at qz.ws.PrintSocketClient.processMessage(Unknown Source)
        at qz.ws.PrintSocketClient.onMessage(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by bberenz** [comment]
Oh, I forgot we changed libraries for Windows. PJHA checks the device open state in all of its calls, but does not allow us to query the open value ourselves..

I've changed the close call to catch and log this exception as an "already closed" status. This should allow the close call to complete successfully and remove the dead device from the connection. So, 20186574a2f55f69a80a9668e117cf4f805a7957 should allow you to re-claim without refreshing. If you could verify again for me please.

**Comment by klabarge** [comment]
> 2018657 should allow you to re-claim without refreshing.

Yes, this patch works. Closing.
