### ISSUE TITLE
Malformed URL printing multiple HTML objects

### ISSUE THREAD

**Issue by tresf** [qzind/tray#368]
This happens when using `sample.html` from 2.0 to print HTML content to 2.1 app.

Sample code:

```js
var data= [
   {
      type: 'html',
      format: 'plain',
      data: '<html><h1>test1</h1></html>'
   },
   {
      type: 'html',
      format: 'plain',
      data: '<html><h1>test2</h1></html>'
   }
];

var config = qz.configs.create('PDFCreator', { scaleContent: false, rasterize: false });
qz.print(config, data).catch(function(err) { console.error(err); });
```
		
```
[ERROR] 2018-10-16 11:53:58,446 @ qz.utils.PrintingUtilities:?
	Failed to print
java.awt.print.PrinterException: Malformed URL
	at qz.printer.action.PrintHTML.print(Unknown Source)
	at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)
[TRACE] 2018-10-16 11:53:58,465 @ qz.utils.PrintingUtilities:?
	Returning processor back to pool
```

**Comment by bberenz** [comment]
Issue was only the first data element would be converted to the 2.1 format, any subsequent elements would use the default flavor, `FILE`.
Fix under 66436d0db1388925569c09bf007e8ed1c5267f5c
