### ISSUE TITLE
NumberFormatException printing to HP on Mac

### ISSUE THREAD

**Issue by tresf** [qzind/tray#37]
Upon investigation, `lpoptions -p laserjet -l` it appears that the resolution is two-part, breaking on our parsing logic.

```diff
HPOption_Tray3/Tray 3: *False Tray3_500 Tray3_250
HPOption_Duplexer/Duplex Unit: True *False
HPPaperPolicy/Fit to Page: *PromptUser NearestSizeAdjust NearestSizeNoAdjust
InstalledMemory/Total Printer Memory: *32MB 48MB 64MB 96MB 160MB 256MB
HPStraightPaperPath/Use Straight Paper Path: True *False
Smoothing/Resolution Enhancement: *PrinterDefault On Off
PageSize/Page Size: *Letter LetterSmall Executive DoublePostcardRotated Legal Legal.Small A4 A4Small A5 ISOB5 B5 FanFoldGermanLegal 7.75x10.75 Env10 EnvMonarch EnvDL EnvC5 EnvISOB5 Custom.WIDTHxHEIGHT
MediaType/Media Type: *None Plain Preprinted Letterhead Transparency Prepunched Labels Bond Recycled Color Rough Card_Stock Envelope
HPBookletFilter/Format Output as Booklet: True *False
HPBookletBackCover/Last Page Is Back Cover: True *False
HPBookletPageOrder/Bind Pages on the Right: True *False
HPBookletScaling/Scaling: *Proportional FitPage
HPBookletPageSize/Paper for Booklet: *Letter LetterSmall Executive DoublePostcardRotated Legal Legal.Small A4 A4Small A5 ISOB5 B5 7.75x10.75 FanFoldGermanLegal
InputSlot/Paper Source: Tray1 *Tray2 Tray3_500 Tray3_250
ManualFeed/Tray 1 (Manual): True *False
HPHalftone/Levels of Gray: *PrinterDefault Enhanced Standard
+ Resolution/Printer Resolution: 1200x1200dpi *600x601dpi 600x600dpi
HPEconoMode/EconoMode: *PrinterDefault True False
Duplex/Two-Sided: *None DuplexNoTumble DuplexTumble
```

Backtrace logs:

```
[DEBUG] 2016-04-22 07:24:52,191 @ qz.utils.ShellUtilities:?
        Executing: [lpstat, -a]
[DEBUG] 2016-04-22 07:24:52,316 @ qz.utils.ShellUtilities:?
        Executing: [lpstat, -l, -p, laserjet]
[INFO] 2016-04-22 07:24:52,332 @ qz.utils.ShellUtilities:?
        laserjet:  laserjet printer
[DEBUG] 2016-04-22 07:24:52,333 @ qz.utils.ShellUtilities:?
        Executing: [lpoptions, -p, laserjet, -l]
[ERROR] 2016-04-22 07:24:52,403 @ qz.ws.PrintSocketClient:?
        Failed to print
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at qz.utils.ShellUtilities.getCupsDensities(Unknown Source)
        at qz.utils.PrintingUtilities.getNativeDensity(Unknown Source)
        at qz.printer.PrintOptions.<init>(Unknown Source)
        at qz.ws.PrintSocketClient.processPrintRequest(Unknown Source)
        at qz.ws.PrintSocketClient.processMessage(Unknown Source)
        at qz.ws.PrintSocketClient.onMessage(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
[TRACE] 2016-04-22 07:24:52,421 @ qz.utils.PrintingUtilities:?
        Returning processor back to pool
```

Proposed fix/test scenario:

```java
String[] densities = {
    "Resolution/Printer Resolution: 200dpi *300dpi 600dpi",
    "Resolution/Printer Resolution: 1200x1200dpi *600x601dpi 600x600dpi"
};

for (String density : densities) {
    String[] parts = density.split("\\s+");
    for (String part : parts) {
        // parse default, i.e. [200dpi *300x300dpi 600dpi]
        if (part.startsWith("*")) {
            int type = part.toLowerCase().contains("dpi") ? PrinterResolution.DPI : PrinterResolution.DPCM;
            int parsed = Integer.parseInt(part.split("x")[0].replaceAll("\\D+", ""));
            System.out.println("Parsed default density from CUPS: " + parsed + (
            type == PrinterResolution.DPI ? "dpi" : "dpcm"));
       }
   }
}
```

**Comment by tresf** [comment]
A few extra changes had to be made... 

 * Per recommendation and via 9438606, the fallback if the density can't be parsed should be a null `PrinterResolution` to prevent a `java.lang.IllegalArgumentException: crossFeedResolution is < 1`
 * Although `Resolution` was sufficient in testing, the HP drivers have an attribute called `Smoothing/Resolution Enhancement:`, so we had to be a bit more specific with our command line parsing.
 * Ubuntu 12.04 uses `Output Resolution:` whereas OS X uses `Printer Resolution:`, so we've added both, as well as simply `Resolution/`.

This should be good for a while until we discover another edge case with the command line output.
