### ISSUE TITLE
Silent error with certificate without Fully Qualified Domain Name

### ISSUE THREAD

**Issue by aktywnitu** [qzind/tray#394]
My mistake was that I created certificate with empty Fully Qualified Domain Name.
Of course such certificate has no sense, but I have not received any information from program logs.
Now I have use certificate with FQDN and all work correctly.
I have tried before run program from commands line and see hidden errors.
I am not sure if is connected with FQDN, but I received below logs:
```

[INFO] 2018-12-14 15:46:13,273 @ qz.deploy.DeployUtilities:?
        Main properties file C:\Program Files\QZ Tray\qz-tray.properties
javax.security.cert.CertificateParsingException
        at qz.auth.Certificate.<init>(Unknown Source)
        at qz.auth.Certificate.<clinit>(Unknown Source)
        at qz.common.TrayManager.addMenuItems(Unknown Source)
        at qz.common.TrayManager.<init>(Unknown Source)
        at qz.ws.PrintSocketServer$1.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.get(Unknown Source)
        ... 19 more
[DEBUG] 2018-12-14 15:46:13,487 @ qz.utils.ShellUtilities:?
        Executing: [C:\WINDOWS\system32\reg.exe, query, HKCU\Software\Microsoft\Windows\CurrentVersion\Run\, /v, QZ Tray]
[DEBUG] 2018-12-14 15:46:14,485 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8283
[DEBUG] 2018-12-14 15:46:14,516 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8384
[DEBUG] 2018-12-14 15:46:14,524 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8485
[INFO] 2018-12-14 15:46:14,550 @ qz.ws.PrintSocketServer:?
        Server started on port(s) 8182, 8181
```

**Comment by tresf** [comment]
I created both an SSL certificate without a FQDN as well as as a licensing/authCert certificate without a FQDN and they both work without any errors.

* My first test, I entered "test" for all items (CN=, OU=, etc).
* My second test, I left them blank for all items.

Neither of these produced any errors.  I was able to create a similar error but not using the DER/base64 formatted certificate but that would make this invalid.

If you can provide steps to reproduce, please share. Otherwise closing as `invalid`.
