### ISSUE TITLE
JDK11 Support

### ISSUE THREAD

**Issue by tresf** [qzind/tray#402]
Oracle is making some EOL announcements for Java 8.  Although originally targeted at Oracle Java SE 8 **JDK**, the information pages are quite unclear about this.

To clear the air, we should move the codebase to Java 11 ASAP.  The biggest hurdle will be packaging JavaFX, which has since been removed from Java 11.

Note, Java 9 and Java 10 are EOL already because they don't carry an "LTS" (long term support) tag.

PR opened #407

**Comment by onurguzel** [comment]
After manually installing JavaFX, I was able to compile QZ Tray with Java 11 for both 2.0 and 2.1 branches. When I launch (on macOS), icon is shown in the tray area, but also throws this exception:

```
This version of Mac OS X does not support the Apple EAWT.  ApplicationEvent handling has been disabled (java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener)
OSXAdapter could not access the About Menu
java.lang.NoSuchMethodException: com.apple.eawt.Application.setEnabledAboutMenu(boolean)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2476)
	at com.apple.OSXAdapter.setAboutHandler(Unknown Source)
	at qz.utils.MacUtilities.registerAboutDialog(Unknown Source)
	at qz.common.TrayManager.addMenuItems(Unknown Source)
	at qz.common.TrayManager.<init>(Unknown Source)
	at qz.ws.PrintSocketServer.lambda$main$0(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by tresf** [comment]
We add some event listeners to get some Apple-specific features (e.g About dialog from native menu bar).

For now we can put Java version detection around these so that it will safely load.

**Comment by tresf** [comment]
@onurguzel QZ Tray with Java 11 is working just fine for me minus the Mac integration and the JavaFX library.  The desktop integration appears to have changed: http://openjdk.java.net/jeps/272

We'd be willing to put a bounty on the integration features but they appear benign for now.

**Comment by tresf** [comment]
For anyone testing against 2.0, please delete `jre/jfxrt.jar` before attempting to run.

There appears to be a bug with javafx11 on Windows.  If the `bin` folder is not added to the path, it'll crash with `Graphics Device initialization failed for : d3d, sw Error initializing QuantumRenderer: no suitable pipeline found`.  We'll need to find a way to add this dynamically at runtime so that we can still launch from console.

For now, a workaround in IntelliJ is to add `PATH=<javafx11>\bin` to the Environmental Variables in IntelliJ.

**Comment by tresf** [comment]
Moved checklist to https://github.com/qzind/tray/pull/407.  This PR is in really good shape and ready for testing.

**Comment by tresf** [comment]
@tresf FYI, access violations should be handled 3c23ec5.

**Comment by tresf** [comment]
Reopening.  The build logic needs to be improved.  It assumes the platform it's building on is the platform that's being targeted, but we build Windows on Linux, etc.  This breaks a few areas in the `build.xml` logic and will need to be reworked.
