### ISSUE TITLE
JNA can't find dependent libraries

### ISSUE THREAD

**Issue by tresf** [qzind/tray#413]
Using OpenJDK11 from AdoptOpenJDK.org on Windows, the "About" dialog raises the following error:

```
Exception in thread "DeviceRemovalHandler" java.lang.UnsatisfiedLinkError: C:\Users\owner\AppData\Local\Temp\jna-106164915\jna1221906576012913996.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:767)
        at java.base/java.lang.System.load(System.java:1831)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at purejavahidapi.windows.Kernel32Library.<clinit>(Kernel32Library.java:43)
        at purejavahidapi.windows.DeviceRemovalHandler$1.run(DeviceRemovalHandler.java:54)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I found an identical backtrace here which suggests updating JNA will fix it: https://github.com/MarkusBernhardt/proxy-vole/issues/35

**Comment by tresf** [comment]
Impact to bumping JNA:
* ✅ jssc's dot NOT use JNA
* ✅ usb4java does NOT use JNA
* ⚠️hid4java DOES use JNA
* ⚠️purjavahidapi DOES use JNA
