### ISSUE TITLE
HID on Windows 10 + Oracle JDK 11

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#424]
I get the same "JNA Cannot find dependent libraries" error as bug report #413 when trying to list HID devices on Windows 10 + Java 11.

I installed JDK 11 [from Oracle's website.](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html)

```cmd
C:\Users\IEUser>java -version
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

```cmd
Exception in thread "DeviceRemovalHandler" java.lang.UnsatisfiedLinkError: C:\Users\IEUser\AppData\Local\Temp\jna--2138670329\jna9784430788779113981.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:767)
        at java.base/java.lang.System.load(System.java:1831)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at purejavahidapi.windows.Kernel32Library.<clinit>(Kernel32Library.java:43)
        at purejavahidapi.windows.DeviceRemovalHandler$1.run(DeviceRemovalHandler.java:54)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by tresf** [comment]
Closed via 217f9da.
