### ISSUE TITLE
HTTP About Page throws NullPointerException when using Trusted CA Cert

### ISSUE THREAD

**Issue by tresf** [qzind/tray#432]
When using a 3rd party SSL certificate provided to the desktop installer (e.g. #73) the HTTP about page throws a `NullPointerException`

```log
2019-03-07 15:17:52,210 [WARN] /
java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.<init>(Unknown Source)
	at org.bouncycastle.asn1.ASN1Primitive.fromByteArray(Unknown Source)
	at org.bouncycastle.x509.extension.X509ExtensionUtil.fromExtensionValue(Unknown Source)
	at qz.common.AboutInfo.ssl(Unknown Source)
	at qz.common.AboutInfo.gatherAbout(Unknown Source)
	at qz.ws.HttpAboutServlet.generateHtmlResponse(Unknown Source)
	at qz.ws.HttpAboutServlet.doGet(Unknown Source)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:224)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)
2019-03-07 15:17:52,408 [WARN] /favicon.ico
java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.<init>(Unknown Source)
	at org.bouncycastle.asn1.ASN1Primitive.fromByteArray(Unknown Source)
	at org.bouncycastle.x509.extension.X509ExtensionUtil.fromExtensionValue(Unknown Source)
	at qz.common.AboutInfo.ssl(Unknown Source)
	at qz.common.AboutInfo.gatherAbout(Unknown Source)
	at qz.ws.HttpAboutServlet.generateHtmlResponse(Unknown Source)
	at qz.ws.HttpAboutServlet.doGet(Unknown Source)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:224)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by tresf** [comment]
Tested with LetsEncrypt certificate and the issue cannot be reproduced.  Need to test again with another certificate issued by another CA (e.g. DigiCert).

**Comment by tresf** [comment]
Tested with AlphaSSL certificate and the issue cannot be reproduced either.

**Comment by bberenz** [comment]
The last line hit in our code appears to be where we check ["rootca" status](https://github.com/qzind/tray/blob/2.0/src/qz/common/AboutInfo.java#L99). The parameter pulled from `x509.getExtensionValue(Extension.basicConstraints.getId())` is passed along untouched until the call at the top of the stacktrace, so it stands to reason that value is somehow null on their custom cert.  
We default to a `false` value on an IOException, and I don't think we ever expected to get a null there (and from your testing here, that seems valid in most cases). But it also shouldn't hurt to add NullPointerException as one of the catch cases and default out there for this edge case.

**Comment by bberenz** [comment]
Extra exception clause added under 3e9353cd89c000701495c9128dfc9ca994eee0e6
