### ISSUE TITLE
Compiling using Java11/AdoptOpenJDK11 - JavaFX errors

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#441]
When I compile the 2.0 branch using AdoptOpenJDK 11 or Oracle Java 11, HTML printing on macOS and Ubuntu does not work. Windows HTML printing works.

openjdk version "11.0.3" 2019-04-16
java version "11.0.2" 2019-01-15 LTS

If I compile using Java8, I am able to run QZ Tray using Java 11 / AdoptOpenJDK11 without issues.

Note, I compiled all installers on macOS when testing.

### macOS
```
[TRACE] 2019-04-13 11:02:08,618 @ qz.printer.action.WebApp:?
	Waiting for JavaFX..
[ERROR] 2019-04-13 11:02:08,874 @ qz.utils.PrintingUtilities:?
	Failed to print
java.lang.UnsupportedOperationException: Unable to start JavaFX service
	at qz.printer.action.PrintHTML.parseData(Unknown Source)
	at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: JavaFX did not start
	at qz.printer.action.WebApp.initialize(Unknown Source)
	... 14 more
[TRACE] 2019-04-13 11:02:08,893 @ qz.utils.PrintingUtilities:?
	Returning processor back to pool
```

### Ubuntu 18.04

```
[TRACE] 2019-04-13 08:15:43,789 @ qz.utils.PrintingUtilities:?
	Returning processor back to pool
[ERROR] 2019-04-13 08:15:43,790 @ qz.ws.PrintSocketClient:?
	Connection error
java.lang.RuntimeException: Cannot call method public void qz.ws.PrintSocketClient#onMessage(org.eclipse.jetty.websocket.api.Session, java.io.Reader) with args: [org.eclipse.jetty.websocket.common.WebSocketSession, org.eclipse.jetty.websocket.common.message.MessageReader]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.unwrapRuntimeException(CallableMethod.java:93)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:75)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedClassVersionError: qz/printer/action/WebApp
	at qz.printer.action.PrintHTML.parseData(Unknown Source)
	at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	... 5 more
```

### Compile output

This looks identical to the Java 8 compile logs, but thought I would share.

```
Kyles-MacBook-Pro:tray kyle$ ant pkgbuild
Buildfile: /Users/kyle/tray/build.xml

pkgbuild-preflight:

init:
     [echo] Building qz-tray using JDK 11

clean:
   [delete] Deleting directory /Users/kyle/tray/out

get-current-platform:

get-javafx-version:

check-javafx-needed:

cleanup-old-javafx:

check-javafx-found:

download-javafx-windows:

download-javafx-mac:

download-javafx-linux:

copy-native-current:
     [echo] javafx.current.extension=dylib

copy-native-platform:
     [copy] Copying 13 files to /Users/kyle/tray/out/dist/libs

copy-native-target:
     [echo] javafx.target.extension=dylib

copy-native-platform:

show-javafx-debug:
     [echo] Windows:
     [echo]  current.platform.windows=${current.platform.windows}
     [echo]  target.platform.windows=${target.platform.windows}
     [echo]  javafx.windows.needed=${javafx.windows.needed}
     [echo]  javafx.windows.found=/Users/kyle/tray/lib/javafx-sdk-11.0.2/bin/glass.dll (before download)
     [echo] 
     [echo] Mac:
     [echo]  current.platform.mac=true
     [echo]  target.platform.mac=true
     [echo]  javafx.mac.needed=true
     [echo]  javafx.mac.found=/Users/kyle/tray/lib/javafx-sdk-11.0.2/lib/libglass.dylib (before download)
     [echo] 
     [echo] Linux:
     [echo]  current.platform.linux=${current.platform.linux}
     [echo]  target.platform.linux=${target.platform.linux}
     [echo]  javafx.linux.needed=${javafx.linux.needed}
     [echo]  javafx.linux.found=/Users/kyle/tray/lib/javafx-sdk-11.0.2/lib/libglass.so (before download)
     [echo] 

download-javafx:

cleanup-javafx-dist:

prepackage:
     [echo] Processing self-signing variables
     [echo] Creating Firefox certificate config files
     [copy] Copying 1 file to /Users/kyle/tray/out/dist/auth/firefox
     [copy] Copying 1 file to /Users/kyle/tray/out/dist/auth/firefox
```

**Comment by tresf** [comment]
Kyle, I just tested this on MacOS and it's working for me.  Can you purge the build directory and try again?

**Comment by klabarge** [comment]
After purging `lib/javafx-sdk-11.0.2` and rebuilding, HTML printing works as expected.
