### ISSUE TITLE
Differentiate between bad signature and bad certificate

### ISSUE THREAD

**Issue by tresf** [qzind/tray#459]
**Problem**

When the "Gateway Dialog" is shown for an invalid signature, it shows a dialog which suggests that the certificate is invalid.  This is confusing to customers as the issue is often a bad signature.

The proposal is to make the dialog accurate as to the problem as well as add better information to this dialog for troubleshooting purposes.  Mockup attached:

![image](https://user-images.githubusercontent.com/6345473/59856480-fb9de900-9344-11e9-9bfb-6b925d4ce8b8.png)

In addition, this enhancement will **finally** allow "always allow" for invalid signatures, limited to that particular session/page refresh/websocket connection.

**Comment by bberenz** [comment]
I've gotten the dialog trust separated from the cert logic, so we always have the unmodified certificate. I opted to change the bolded text to show the presice issue instead of the cert link. Currently available on the `ui-update` branch.
![dialog-trust](https://user-images.githubusercontent.com/5912715/60750193-f65eb200-9f72-11e9-98d4-178ae030b598.png)

But can you explain the purpose behind the proposed "Signature" dialog? Not sure I fully understand what you want for that one.

**Comment by tresf** [comment]
The signature screen is for troubleshooting.  When the signature is wrong, often it's obvious in the JSON, such as:
1. Incorrect flavor
2. 404

Currently to troubleshoot this live requires reviewing the logs, which is very cumbersome from the log window since the signature is at the end of a potential very long string or worse, requires CMD from the Desktop to see it live.  This will make support easier.

**Comment by tresf** [comment]
I'd like to use some form of "partial trust" icon in this scenario, such as a blue shield with a warning icon.

**Comment by tresf** [comment]
I've pinged @budislav for shield proposals.   @bberenz I hope you don't mind, I'm sharing your mockup here, so that we have it in context.

![image](https://user-images.githubusercontent.com/6345473/61173358-47b50580-a560-11e9-9316-f780172bc76b.png)

**Comment by bberenz** [comment]
Updated the `ui-update` branch with the new details dialog:

![complete](https://user-images.githubusercontent.com/5912715/61573010-7efe4780-aa75-11e9-9d1f-908cca530bc2.png)

I altered the shield icon you sent me to the same yellow as the warning icon as a temporary fill until you get the official one in.

**Comment by tresf** [comment]
@bberenz this looks great.  I think "View request details" should be red and the `(Expired)` text should be next to the timestamp, not next to the Signature block, or perhaps in a dedicated "Validity" row so that we can have an area for "Verified | Expired | Invalid", etc.  Thoughts?

**Comment by bberenz** [comment]
Changes have been integrated. Went with a dedicated row for the status since I think it looks easier to read. But I also changed the timestamp to be highlighted red for expired requests instead of the signature.

**Comment by tresf** [comment]
@bberenz I'm getting a NPE if the certificate is blank.

Perhaps?

```diff
diff --git a/src/qz/ui/component/RequestTable.java b/src/qz/ui/component/RequestTable.java
index 728bbdd..6d265fd 100644
--- a/src/qz/ui/component/RequestTable.java
+++ b/src/qz/ui/component/RequestTable.java
@@ -93,7 +93,7 @@ public class RequestTable extends DisplayTable {
             }
 
             // Second Column
-            if (request == null || col < 1) { return stylizeLabel(STATUS_NORMAL, label, isSelected); }
+            if (request == null || col < 1 || table.getValueAt(row, col - 1) == null) { return stylizeLabel(STATUS_NORMAL, label, isSelected); }
 
             RequestField field = (RequestField)table.getValueAt(row, col - 1);
             int style = STATUS_NORMAL;
```

**Comment by bberenz** [comment]
I can't seem to replicate the NPE, but I've made a change to handle 'no cert' connections a bit better. 
Can you see if that solves it for you? Otherwise I'll need your steps to reproduce.

**Comment by tresf** [comment]
> steps to reproduce.

I've tried to reproduce this by resetting to commit e840d2e and it's completely sporadic, which is very concerning.  Is there a chance there's a race condition causing this?

I'm not conformable confirming the patch unless I can have a before/after and currently I'm struggling to reproduce.

**Comment by tresf** [comment]
It just happened again... 

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at qz.ui.component.RequestTable$RequestTableCellRenderer.getTableCellRendererComponent(RequestTable.java:100)
	at javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7037)
	at javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7424)
	at javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:6938)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:632)
	at javax.swing.JTable.tableRowsInserted(JTable.java:4477)
	at javax.swing.JTable.tableChanged(JTable.java:4413)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
	at javax.swing.table.DefaultTableModel.insertRow(DefaultTableModel.java:376)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:350)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:361)
	at qz.ui.component.DisplayTable.autoSize(DisplayTable.java:55)
	at qz.ui.component.RequestTable.autoSize(RequestTable.java:76)
	at qz.ui.DetailsDialog.updateDisplay(DetailsDialog.java:55)
	at qz.ui.GatewayDialog.lambda$initComponents$0(GatewayDialog.java:76)
	at qz.ui.component.LinkLabel$4.mouseClicked(LinkLabel.java:104)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at qz.ui.GatewayDialog.prompt(GatewayDialog.java:214)
	at qz.common.TrayManager.lambda$showGatewayDialog$3(TrayManager.java:377)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bberenz** [comment]
a15d4f74d5ff849940672b0322ae8594c5125b72 adds an extra null check on the value you are getting a null from.

**Comment by tresf** [comment]
Thanks, that seems to have fixed the sporadic bug.  Back to @klabarge for final review.

**Comment by klabarge** [comment]
So far I've tested the below scenarios, all look good!

* valid signature
* missing certificate
* missing private key (this is nice, error from web controller is in the signature field)
* miss matching key pair

Once scenario I haven't tested was an expired private key. I'm still trying to find some old keys laying around.

**Comment by klabarge** [comment]
On second thought, I have a few suggestions:

1. what do you think about changing the "Not Required" and "Invalid" text from red to yellow just for the certificate shield?

   <img width="506" alt="image" src="https://user-images.githubusercontent.com/12505463/62172953-298e2a00-b302-11e9-9bb7-5bcc1d4f36d9.png">

2. When the certificate is expired, it shows up as "invalid" on both the initial dialogue and the request details. Can we add "Expired Certificate" to the dialogue, much like how you have ["Expired Signature" for this one](https://github.com/qzind/tray/issues/459#issuecomment-513428558)

    <img width="397" alt="image" src="https://user-images.githubusercontent.com/12505463/62173205-31020300-b303-11e9-8504-5439043fa9a6.png">

**Comment by tresf** [comment]
> what do you think about changing the "Not Required" and "Invalid" text from red to yellow just for the certificate shield?

I would say just make "Not Required" black/regular color.  "Validity" can stay red or go black/regular.  Unfortunately, yellow is the lightest of the primary colors, so it [never sits well against a light background](https://user-images.githubusercontent.com/6345473/62180090-a5956b80-b31c-11e9-876c-a7c9fcf4486b.png).

**Comment by bberenz** [comment]
Latest changes take color off the "Not Required" text when connecting and provide a message for bad certificate as well as signatures.

![futuretype](https://user-images.githubusercontent.com/5912715/62594774-bcead080-b8a9-11e9-9aa7-41365a5d5a1f.png)

**Comment by klabarge** [comment]
@bberenz tested the changes and everything looks good. 👍 

![image](https://user-images.githubusercontent.com/12505463/62667575-4821a000-b956-11e9-88a7-c0861ec33195.png)
