### ISSUE TITLE
JSONArray is not a JSONObject

### ISSUE THREAD

**Issue by tresf** [qzind/tray#502]
When using QZ Tray 2.1 the follow code fails:

2.0 format:
```js
printData = [
    {
        type: 'raw',
        format: 'image',
        data: 'assets/img/image_sample_bw.png',
        options: { language: 'escp', dotDensity: 'single' }
    },  
    '\x1B' + '\x40',          // init
    '\x1D' + '\x56'  + '\x01' // partial cut (new syntax)
];
```

2.1 format:
```js
printData = [
    {
        type: 'raw',
        format: 'image',
        flavor: 'file',
        data: 'assets/img/image_sample_bw.png',
        options: { language: 'escp', dotDensity: 'single' }
    },
    '\x1B' + '\x40',          // init
    '\x1D' + '\x56'  + '\x01' // partial cut (new syntax)
];
```

```
[ERROR] 2019-10-17 12:43:26,673 @ qz.utils.PrintingUtilities:?
	Failed to print
org.codehaus.jettison.json.JSONException: JSONArray[1] is not a JSONObject.
	at org.codehaus.jettison.json.JSONArray.getJSONObject(JSONArray.java:277)
	at qz.printer.action.PrintImage.parseData(Unknown Source)
	at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)
[TRACE] 2019-10-17 12:43:26,680 @ qz.utils.PrintingUtilities:?
	Returning processor back to pool
```

**Comment by momoko-squid** [comment]
Any idea what is the problem? 
(I reported this bug originally)

**Comment by tresf** [comment]
It's most likely an internal error within Java.  It's been assigned out, we'll have more soon.

**Comment by momoko-squid** [comment]
Is it possible to have it worked on now?
There is going to be a deployment tomorrow...

**Comment by momoko-squid** [comment]
Hello Tres, I've debugged the exception and have zoomed in to the point of the error.
It comes from PrintImage.parseData(). When we have a printer as the first record in the data array:
    { type:'raw', format:'image', flavor:'file', data: image_url, options:{language:'escp'}},

The execution goes through, but when the next iteration comes, there's no more JSON record, now there's only ESCPOS commands..

    '\x1B' + '\x40',            // init
    '\x1B' + '\x44' + '\x1B' + '\x23' + '\x00', // Define 2 tabstops at 27th and 35th column
    '\x1B' + '\x61' + '\x31',   // center align
    '\x1B' + '\x45' + '\x01',   // emphasized mode on

So the code with hit an exception here:
                data = printData.getJSONObject(i);
This will give the dreaded **JSONArray is not a JSONObject
#502**, because it is NOT a JSON. I used printData.get(i) to get the ESCPOS data out.

Here's what I did until now:
            try {
                data = printData.getJSONObject(i);
                log.debug("data=" + data.toString());
            } catch (JSONException e) {
                log.debug("screwed up!!");
                continue;
            }

I wrapped                 data = printData.getJSONObject(i);
around a try/catch block. If it hits a ESCPOS command it'll continue with the loop, thereby winding up the array.

In this way, I am able to get the 
    { type:'raw', format:'image', flavor:'file', data: image_url, options:{language:'escp'}},

printed out. But the problem is that the **ESCPOS data DOES NOT** get printed.

Any clues?

/waisun
p.s. this is my first time troubleshooting Java code. I've never done Java before. I'm a C/C++/PHP/Javascript guy.

**Comment by tresf** [comment]
> Any clues?

We'll be fixing this as soon as possible.  The fix will involve:
1. Wrapping the array into an object<br>--OR--
1. Reading the array as an array.

If you want to patch it yourself you are free to submit a PR, but we'll have it fixed shortly regardless of your efforts.

Note, we won't accept a solution which blindly swallows an exception.

**Comment by momoko-squid** [comment]
No worries. My efforts is just for myself to study the code and to gain more understanding of the internals. But I am not able to get the ESCPOS printed out after printing the logo image.

**Comment by momoko-squid** [comment]
Tres,
It'd be great if you can explain to me execution path for having an image/ESCPOS and just ECSPOS only is so different.

This is for an image/ESCPOS. The result is that the image was printed out
2019-10-19 03:13:59,233 [DEBUG] i=48
2019-10-19 03:13:59,233 [DEBUG] printData[48]=V
2019-10-19 03:13:59,233 [DEBUG] Parsed 1 images for printing
2019-10-19 03:13:59,233 [DEBUG] ***** params.getJSONObject('printer') *****
2019-10-19 03:13:59,233 [DEBUG] {"name":"Receipt"}
2019-10-19 03:13:59,234 [DEBUG] options=qz.printer.PrintOptions@25d126a7
2019-10-19 03:13:59,234 [DEBUG] ***** BEFORE processor.print() *****
2019-10-19 03:13:59,238 [INFO] Starting printing (1 copies)
2019-10-19 03:13:59,243 [WARN] Supported printer densities not found
2019-10-19 03:13:59,300 [DEBUG] Scaling image up by x1.0
2019-10-19 03:13:59,303 [DEBUG] Paper area: 0,0:204,595
2019-10-19 03:13:59,303 [DEBUG] Memory: 96m/3492m
2019-10-19 03:13:59,733 [INFO] Printing complete        


----------------\n","\u001ba1","1060000260000000061\n","\u001ba1","Thank You!\n","\n","\u001dV\u0001"]
2019-10-19 03:14:31,741 [DEBUG] ***** BEFORE processor.parseData() *****
2019-10-19 03:14:31,757 [DEBUG] ***** params.getJSONObject('printer') *****
2019-10-19 03:14:31,757 [DEBUG] {"name":"Receipt"}
2019-10-19 03:14:31,758 [DEBUG] options=qz.printer.PrintOptions@69b9449d
2019-10-19 03:14:31,758 [DEBUG] ***** BEFORE processor.print() *****
2019-10-19 03:14:31,763 [DEBUG] Printing to file: qz_raw_1726063681686670559.tmp
2019-10-19 03:14:31,764 [DEBUG] Executing: [lp, -d, Receipt, -o, raw, /tmp/qz_raw_1726063681686670559.tmp]
2019-10-19 03:14:31,784 [INFO] Printing complete 
> > Any clues?
> 
> We'll be fixing this as soon as possible. The fix will involve:
> 
> 1. Wrapping the array into an object--OR--
> 2. Reading the array as an array.
> 
> If you want to patch it yourself you are free to submit a PR, but we'll have it fixed shortly regardless of your efforts.
> 
> Note, we won't accept a solution which blindly swallows an exception.

**Comment by momoko-squid** [comment]
Tres, any progress on this front? I would like to help but my knowledge of the internals is very limited. I am not understanding the dataflow, and the parsing logic, especially for my use case of raw printing with initial logo image.

**Comment by tresf** [comment]
We're already obliged to fix, no need to bump this.
