### ISSUE TITLE
Unhandled rejection ReferenceError: screen is not defined

### ISSUE THREAD

**Issue by tresf** [qzind/tray#543]
Running QZ Tray (2.0 and 2.1) with Node.js using `bluebird` for Promises the following error is thrown:

```
Unhandled rejection ReferenceError: screen is not defined
    at W3CWebSocket._qz.websocket.connection.sendData (C:\Users\owner\node_modules\qz-tray\qz-tray.js:219:32)
    at sendCert (C:\Users\owner\node_modules\qz-tray\qz-tray.js:323:50)
    at tryCatcher (C:\Users\owner\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\owner\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\owner\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\owner\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\owner\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\owner\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\owner\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\owner\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\owner\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

This error isn't immediately obvious with other Promise implementations as the rejection isn't propagating properly.

The issue appears to be the use of `screen` without checking if the variable has been defined.

**Comment by tresf** [comment]
Closed via d38c984.  Backported to 2.0 via 066b0c6.
