### ISSUE TITLE
InvocationTargetException starting QZ Tray macOS Catalina

### ISSUE THREAD

**Issue by tresf** [qzind/tray#572]
It appears awt/swing gets a null graphics context when trying to initialize the GUI when using the JCD381 USB-C Dual HDMI Mini Dock from j5create.  (We've reached out to j5create and opened Zendesk `Ticket #105995`)

We're not sure if this bug is with the j5create driver implementation or the JDK itself.

* **OS:** macOS Catalina 10.15.4
* **Java:** AdoptOpenJDK 11.0.6
* **Hardware:** j5create JCD381 USB-C dock

Workaround:  Unplugin this adapter.

Interestingly, even a simple Hello World example fails on this adapter.  The same test succeeds when the adapter is unplugged.

<details>
<summary><a href="#"><code>HelloWorld.java</code></a></summary>

```java
import javax.swing.*;

public class HelloWorld {
    public static void main(String ... args) throws Exception {
        SwingUtilities.invokeAndWait(() -> JOptionPane.showMessageDialog(null, "Hello world!"));
    }
}
```
</details>

QZ Tray's crash:
```
[ERROR] 2020-01-27 15:02:40,697 @ qz.ws.PrintSocketServer:?
Could not start tray manager
   java.lang.reflect.InvocationTargetException
      at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
      at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
      at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
      at qz.ws.PrintSocketServer.main(Unknown Source)
   Caused by: java.lang.ExceptionInInitializerError
      at qz.ui.tray.TrayType.init(Unknown Source)
      at qz.ui.tray.TrayType.init(Unknown Source)
      at qz.common.TrayManager.<init>(Unknown Source)
      at qz.ws.PrintSocketServer.lambda$main$0(Unknown Source)
      at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
      at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
      at java.base/java.security.AccessController.doPrivileged(Native Method)
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
      at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
      at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
      at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
   Caused by: java.lang.NullPointerException
      at java.desktop/java.awt.Window.init(Window.java:509)
      at java.desktop/java.awt.Window.<init>(Window.java:549)
      at java.desktop/java.awt.Frame.<init>(Frame.java:423)
      at java.desktop/java.awt.Frame.<init>(Frame.java:388)
      at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
      at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
      at java.desktop/javax.swing.JDialog.<init>(JDialog.java:273)
      at java.desktop/javax.swing.JDialog.<init>(JDialog.java:207)
      at java.desktop/javax.swing.JDialog.<init>(JDialog.java:180)
      at org.jdesktop.swinghelper.tray.JXTrayIcon.<clinit>(Unknown Source)
      ... 17 more
```

**Comment by tresf** [comment]
The j5create adapter which caused this problem is slated to arrive today.

**Comment by tresf** [comment]
The adapter hasn't arrived but support got back with the following information:

> Hello Tres,
>
> * We have been able to partially determine the what might be causing this issue.
> * We have been able to test with two separate Mac computers; Macbook 15-inch Pro 2017 (MacBookPro14,3) & Macbook  12-inch 2016 (MacBook9,1).
>    * On both MacBooks, we were running Java AdoptOpenJDK 11.0.6.
>    * The version of macOS on the MacbookPro14,3 was macOS 10.15.4 Beta 1. The version on the MacBook9,1 was macOS 10.15.3.
>    * We tested the JCD381 using our driver version 3.3-2019-12.05a.
> 
> The most notable difference between the two MacBook computers is that, the MacBookPro14,3 uses both an integrated (Intel HD Graphics 630) and discrete (AMD Radeon Pro 555) graphics adapter, while the MacBook9,1 is only using an integrated (Intel HD Graphics 515) graphics adapter. 
> 
> While running a simple Java HelloWorld on the MacBookPro14,3, we have seen that the graphics adapter switches to the discrete AMD Radeon Pro 555, which we believe to be the issue. (see video below) (**Edit:** removed)
>
> This is likely an issue because, the j5create USB display adapter runs solely off of the integrated graphics adapter of the computer. 
> 
> * While testing the MacbookPro14,3, we did not see the issue while the built-in display was the main display.
> * However, the issue is recreated while the MacBook is in clam-shell and/or while a USB display is the main display.
>    * Test Video: (**Edit:** removed)
>
> * While testing the MacBook9,1, we were not able to recreate the issue, regardless of if the built-in display or external displays are the main display.
>    * Test Video: (**Edit:** removed)
>
> We will look further into this issue, to try to determine if this may be resolved through alternations to the j5create USB display driver.
>
> Thank you for bringing this matter to our attention!

**Comment by tresf** [comment]
Marking as `not our bug` and closing since j5create has reproduced this issue.  Note, I couldn't reproduced on my MacBook pro suggesting that it is limited to laptops with discrete graphics adapters as suspected.
