### ISSUE TITLE
qz.serial.sendData in version 2.1.0 not working

### ISSUE THREAD

**Issue by niloc-ray** [qzind/tray#600]
Hi im trying to open a cash draw in epos j-100 (https://www.infinityepos.com/products/p2c-j-100-colour-coded-waterproof-epos-system-ip66-fanless-all-in-one) with its build in port. The port emulates a serial port and uses a simple ESC p command.

Code:

    function open_cash_drawer_test(cash_drawer_port_number) {
    if (!qz.websocket.isActive()) {
        qz.websocket.connect();
    }
    if (qz.websocket.isActive()) {
        var params = {
            baudRate: '9600',
            dataBits: '8',
            stopBits: '1',
            parity: 'NONE'
        };
        var data = String.fromCharCode(27) + String.fromCharCode(112);

        qz.serial.openPort('COM'+cash_drawer_port_number, params).then(function() { 
            console.log('COM'+cash_drawer_port_number+' open');
            qz.serial.sendData('COM'+cash_drawer_port_number, data).then(function() { 
                console.log('send '+data);
                qz.serial.closePort('COM'+cash_drawer_port_number).then(function() { 
                    console.log('COM'+cash_drawer_port_number+' close');
                }).catch(function(err) {
                    console.error(err);
                });
            }).catch(function(err) {
                console.error(err);
            });    
        }).catch(function(err) {
            console.error(err);
        });
    }
    }

the above code works fine on version 2.0.11.

However on version 2.1.0 i get an error:
2020-03-03 23:59:48,949 [DEBUG] Sending data over [COM4]
2020-03-03 23:59:48,950 [ERROR] Problem processing message
java.lang.NullPointerException
	at qz.communication.SerialIO.sendData(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:227)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
	at java.lang.Thread.run(Unknown Source)

Im not sure if this is a bug or my code.

**Comment by tresf** [comment]
> Im not sure if this is a bug or my code.

I think it's a bit of both.

In 2.1 we [deprecated `options.start`](https://github.com/qzind/tray/blob/a7843f975c53329724315a596f2cb55c53c5b13c/js/qz-tray.js#L1360) in favor of [`options.rx.start`](https://github.com/qzind/tray/blob/master/js/qz-tray.js#L1364), but we seem to have never updated the wiki to reflect this, but since we still support the old syntax for now, that's not the cause.

In 2.0, the API documents, it shows [`options.rx.start` as having a default value of `0x02` when non is provided](https://github.com/qzind/tray/blob/d0b320cb80d043f6da2c64c2b56adca76def7220/js/qz-tray.js#L992) however, I don't think we honor this anymore.

This means to use this parameter, it needs to be specified (either in the deprecated format or in the new format) to be honored starting with 2.1. I'm not sure if this was intentional though so I'll ping @bberenz on it.

So manually providing   `options.start=\x02`, `options.end=\x0D` may very well fix this.  Whether or not this should be default in 2.1 is going to be a decision we make, thanks for pointing this out.

**Comment by bberenz** [comment]
2.1 should honor the old 2.0 default start/end bounds if the options.rx object is not provided (which it looks like it's not), so this definitely looks like a bug on our side.

**Comment by niloc-ray** [comment]
I tried the same function with:

        var params = {
            baudRate: '9600',
            dataBits: '8',
            stopBits: '1',
            parity: 'NONE',
            rx: {
                start: '\x02',
                end: '\x0D'
            }

And:

        var params = {
            baudRate: '9600',
            dataBits: '8',
            stopBits: '1',
            parity: 'NONE',
            start: '\x02',
            end: '\x0D'
        };

Alas no change i still get the error. Just thought i would give it a try. Still works fine on V2.0.

**Comment by tresf** [comment]
I modified the code to communicate with my scale.  I tested this on 2.1.0's sample.html as well as 2.0.11's sample.html.  They both work fine without providing `start`|`end`.  Below is the exact code.

Some notes:

* Always `return` your promises so your indents are only one deep, this makes it easier to read.
* Only `.catch(...)` when you need to.  In most cases, it can be assumed it'll throw all the way up the stack and only `.catch(...)` once.

Besides that, I'm not sure why your code is failing in 2.1.  Both the Java application as well as the API seems to behaving properly in my tests.

```js
var params = {
    baudRate: '9600',
    dataBits: '7',         // Changed from '8'
    stopBits: '1',
    parity: 'EVEN',        // Changed from 'NONE'
    flowControl: 'NONE',   // Added
    // start: '\x02',      // Removed
    // end: '\x0D'         // Removed
};

var port = '/dev/tty.usbserial-AE01KJTG'; // or COM1, etc
var data = 'W\n';                         // command to get weight from scale

qz.serial.setSerialCallbacks(function(evt) {
    console.log('Serial', evt.type == 'ERROR' ? evt.exception : evt.portName + 'received output: ' + evt.output);
    qz.serial.closePort(port);
});

qz.websocket.connect().then(function() {
    return qz.serial.openPort(port, params)
}).then(function() { 
    console.log(port + ' open');
    return qz.serial.sendData(port, data);
}).then(function() {
    console.log('send ' + data);
    // return qz.serial.closePort(port);
}).catch(function(err) {
    console.error(err);
});
```

**Comment by niloc-ray** [comment]
Hi i have tried your code:

    function com_port_test()
    {
        var params = {
            baudRate: '9600',
            dataBits: '7',         // Changed from '8'
            stopBits: '1',
            parity: 'EVEN',        // Changed from 'NONE'
            flowControl: 'NONE',   // Added
            // start: '\x02',      // Removed
            // end: '\x0D'         // Removed
        };
        
        var port = 'COM4'; // or COM1, etc
        var data = 'W\n';                         // command to get weight from scale
        
        qz.serial.setSerialCallbacks(function(evt) {
            console.log('Serial', evt.type == 'ERROR' ? evt.exception : evt.portName + 'received output: ' + evt.output);
            qz.serial.closePort(port);
        });
        
        qz.websocket.connect().then(function() {
            return qz.serial.openPort(port, params)
        }).then(function() { 
            console.log(port + ' open');
            return qz.serial.sendData(port, data);
        }).then(function() {
            console.log('send ' + data);
            // return qz.serial.closePort(port);
        }).catch(function(err) {
            console.error(err);
        });
    }

chrome log:
com_port_test()
undefined
qz-tray.js:37 Established connection with QZ Tray on ws://localhost:8182
pos.js DEBUG: 

mv0Mq3+FddtICb9line2wSYF7Oc9KZm2sQAU+443N+jMOaUBIuLcwcya4PcbFEmekr1GhBLHfLMlrXj4VPxiOMrS8GoBthLgvePR1Ae1nMl8O8mt1T+sPOuY7GRYaAqHkrMZPmkudiUYc+vG178pf4jkm8vDabUG7YVCRFBr/WA/Sjt8c11a1I8OORKL93w8nY/q/1eI3hO+JDRfBfgWx8fnLLd4fd0k599HR8TmdKi5UEPRwfo3WbczLMllhYon6CrVk8Pu81lYh9Eq9UoS2vrls5uooguIYHdybr4lzniGc4qya9+ENYqDo3u8VR4fHHfT7KyhiXo1ZwuwhJ62bg==
pos.js?1583452007:355 COM4 open
pos.js?1583452007:52 DEBUG: 

hkDDI/uz63bh8UcZaB5U/6p0k0hklA2chdwpfqK6Y4yyt74UuXYAyECgqRlItTqSfIn4Iirf8/otpNF1MIlc9JQJZjNdHBqE+tbXAmQ+UlAPJdZpSgLkGZCZSxVESnQ7EFcry1j1kuHoTsL9hl9N/VQ5Gk5q/sfjHIfQpWAH2R7qTHeanO6NZVBQLvvKdq4YjD5ew3jJkvv2DTppJktJE2U2sxU+wCI9vLch9+B9zi3sIKTB/j8JW3R7b/b3yd13uBiteSa5cvt1E3FRAlUv+Aw19gKzO1tJ190/ro8r1Rzz9UIfeuUAZwwuL3i8u2fKEr8WQBBgA3DruP4UUEQzkw==
pos.js?1583452007:361 Error: NullPointerException
    at WebSocket._qz.websocket.connection.onmessage (qz-tray.js:260)
(anonymous) @ pos.js?1583452007:361
lib$rsvp$$internal$$tryCatch @ rsvp-3.1.0.min.js:10
lib$rsvp$$internal$$invokeCallback @ rsvp-3.1.0.min.js:10
lib$rsvp$$internal$$publish @ rsvp-3.1.0.min.js:10
lib$rsvp$$internal$$publishRejection @ rsvp-3.1.0.min.js:10
lib$rsvp$asap$$flush @ rsvp-3.1.0.min.js:10
characterData (async)
(anonymous) @ rsvp-3.1.0.min.js:10
lib$rsvp$asap$$asap @ rsvp-3.1.0.min.js:10
lib$rsvp$$internal$$reject @ rsvp-3.1.0.min.js:10
rejectPromise @ rsvp-3.1.0.min.js:10
_qz.websocket.connection.onmessage @ qz-tray.js:260


qz tray log:
2020-03-05 23:47:03,314 [DEBUG] Received new certificate from connection through 51120
2020-03-05 23:47:03,394 [DEBUG] Message: {"call":"serial.openPort","promise":{},"params":{"port":"COM4","bounds":{"baudRate":"9600","dataBits":"7","stopBits":"1","parity":"EVEN","flowControl":"NONE"}},"signature":"mv0Mq3+FddtICb9line2wSYF7Oc9KZm2sQAU+443N+jMOaUBIuLcwcya4PcbFEmekr1GhBLHfLMlrXj4VPxiOMrS8GoBthLgvePR1Ae1nMl8O8mt1T+sPOuY7GRYaAqHkrMZPmkudiUYc+vG178pf4jkm8vDabUG7YVCRFBr/WA/Sjt8c11a1I8OORKL93w8nY/q/1eI3hO+JDRfBfgWx8fnLLd4fd0k599HR8TmdKi5UEPRwfo3WbczLMllhYon6CrVk8Pu81lYh9Eq9UoS2vrls5uooguIYHdybr4lzniGc4qya9+ENYqDo3u8VR4fHHfT7KyhiXo1ZwuwhJ62bg==","timestamp":1583452023316,"uid":"o41roj"}
2020-03-05 23:47:03,458 [DEBUG] Message: {"call":"serial.sendData","promise":{},"params":{"port":"COM4","data":"W\n"},"signature":"hkDDI/uz63bh8UcZaB5U/6p0k0hklA2chdwpfqK6Y4yyt74UuXYAyECgqRlItTqSfIn4Iirf8/otpNF1MIlc9JQJZjNdHBqE+tbXAmQ+UlAPJdZpSgLkGZCZSxVESnQ7EFcry1j1kuHoTsL9hl9N/VQ5Gk5q/sfjHIfQpWAH2R7qTHeanO6NZVBQLvvKdq4YjD5ew3jJkvv2DTppJktJE2U2sxU+wCI9vLch9+B9zi3sIKTB/j8JW3R7b/b3yd13uBiteSa5cvt1E3FRAlUv+Aw19gKzO1tJ190/ro8r1Rzz9UIfeuUAZwwuL3i8u2fKEr8WQBBgA3DruP4UUEQzkw==","timestamp":1583452023412,"uid":"g9aoih"}
2020-03-05 23:47:03,459 [DEBUG] Sending data over [COM4]
2020-03-05 23:47:03,459 [ERROR] Problem processing message
java.lang.NullPointerException
	at qz.communication.SerialIO.sendData(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:227)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
	at java.lang.Thread.run(Unknown Source)
2020-03-05 23:48:46,176 [INFO] Connection closed: 1001 - null
2020-03-05 23:48:46,176 [INFO] Closing all communication channels for
2020-03-05 23:48:46,292 [INFO] Serial port [COM4] closed successfully.

i have also added the com_port_test function to the sample.html and as you has said it works on both 2.0 and 2.1 so it must be something to do with my code else where.  Its has me quite baffled.

Thanks for your time.

**Comment by niloc-ray** [comment]
Fixed it... i had not updated the qz-tray.js file on the server for a while (project has been under development for some time now)

Sorry about that.

**Comment by tresf** [comment]
Thanks for the update!  If this problem comes back with the newer files, let us know!
