### ISSUE TITLE
HTML throws exception when Monocle is disabled

### ISSUE THREAD

**Issue by tresf** [qzind/tray#627]
On 2.0 branch, the following exception occurs on certain machines when Monocle is disabled:
https://gist.github.com/lite1979/e0c75384fd0bcae66d769bb8bcc00460

```
java.lang.NullPointerException
        at com.sun.javafx.webkit.prism.WCPageBackBufferImpl.validate(WCPageBackBufferImpl.java:102)
        at com.sun.webkit.WebPage.paint(WebPage.java:694)
         ...
Exception in snapshot runnable
java.lang.IllegalArgumentException: Unrecognized image loader: null
        at javafx.scene.image.WritableImage.loadTkImage(WritableImage.java:278)
        ...
```

Related: https://bugs.openjdk.java.net/browse/JDK-8139842

We need a way to catch this exception and fallback to a sane zoom.

**Comment by tresf** [comment]
Closed via #628
