### ISSUE TITLE
DtrustedRootCert dosent work - Error loading override cert: override.crt

### ISSUE THREAD

**Issue by thbl** [qzind/tray#636]
Generate cert
`openssl req -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout server.key -out override.crt`

**override.crt** located in QZ Tray root folder

Running `java -Xms512M -DtrustedRootCert=override.crt -jar qz-tray.jar
` from the wigi gives this error

```
C:\Program Files\QZ Tray>java -Xms512M -DtrustedRootCert=override.crt -jar qz-tray.jar
[INFO] 2020-05-12 08:47:29,232 @ qz.ws.PrintSocketServer:?
        QZ Tray version: 2.1.0+1
[INFO] 2020-05-12 08:47:29,234 @ qz.ws.PrintSocketServer:?
        QZ Tray vendor: QZ Industries, LLC
[INFO] 2020-05-12 08:47:29,236 @ qz.ws.PrintSocketServer:?
        Java version: 1.8.0+101
[INFO] 2020-05-12 08:47:29,242 @ qz.ws.PrintSocketServer:?
        Java vendor: Oracle Corporation
[INFO] 2020-05-12 08:47:29,731 @ qz.installer.certificate.CertificateManager:?
        Try to find SSL properties file...
[INFO] 2020-05-12 08:47:29,815 @ qz.installer.certificate.CertificateManager:?
        Found C:\Program Files\QZ Tray/qz-tray.properties
[DEBUG] 2020-05-12 08:47:29,819 @ qz.utils.ShellUtilities:?
        Executing: [net, session]
[INFO] 2020-05-12 08:47:29,905 @ qz.installer.certificate.CertificateManager:?
        Wrote Cert: "C:\Users\xx\AppData\Local\Temp\root-ca-4805961176642255818.crt"
[INFO] 2020-05-12 08:47:29,917 @ qz.installer.certificate.WindowsCertificateInstaller:?
        Opening SYSTEM store using Crypt32...
[DEBUG] 2020-05-12 08:47:29,927 @ qz.installer.certificate.CertificateManager:?
        Parsed hostNames: localhost, localhost.qz.io
[INFO] 2020-05-12 08:47:29,929 @ qz.installer.certificate.CertificateManager:?
        Email address support@qz.io found, assuming CertProvider is INTERNAL
[DEBUG] 2020-05-12 08:47:29,930 @ qz.utils.ShellUtilities:?
        Executing: [CheckNetIsolation.exe, LoopbackExempt, -a, -n=Microsoft.MicrosoftEdge_8wekyb3d8bbwe]
[WARN] 2020-05-12 08:47:29,972 @ qz.installer.WindowsInstaller:?
        Could not whitelist loopback connections for IE, Edge
[INFO] 2020-05-12 08:47:29,998 @ qz.ws.PrintSocketServer:?
        Starting QZ Tray 2.1.0+1
[ERROR] 2020-05-12 08:47:30,686 @ qz.auth.Certificate:?
        Using override cert: override.crt
[ERROR] 2020-05-12 08:47:30,700 @ qz.auth.Certificate:?
        **Error loading override cert: override.crt**
javax.security.cert.CertificateParsingException
        at qz.auth.Certificate.<init>(Unknown Source)
        at qz.auth.Certificate.setOverrideCert(Unknown Source)
        at qz.auth.Certificate.checkOverrideCertPath(Unknown Source)
        at qz.auth.Certificate.<clinit>(Unknown Source)
        at qz.common.TrayManager.addMenuItems(Unknown Source)
        at qz.common.TrayManager.<init>(Unknown Source)
        at qz.ws.PrintSocketServer.lambda$main$0(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.get(Unknown Source)
        ... 21 more
[ERROR] 2020-05-12 08:47:30,702 @ qz.auth.Certificate:?
        Using override cert: C:\Program Files\QZ Tray\override.crt
[ERROR] 2020-05-12 08:47:30,703 @ qz.auth.Certificate:?
        Error loading override cert: C:\Program Files\QZ Tray\override.crt
javax.security.cert.CertificateParsingException
        at qz.auth.Certificate.<init>(Unknown Source)
        at qz.auth.Certificate.setOverrideCert(Unknown Source)
        at qz.auth.Certificate.checkOverrideCertPath(Unknown Source)
        at qz.auth.Certificate.<clinit>(Unknown Source)
        at qz.common.TrayManager.addMenuItems(Unknown Source)
        at qz.common.TrayManager.<init>(Unknown Source)
        at qz.ws.PrintSocketServer.lambda$main$0(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.get(Unknown Source)
        ... 21 more
[DEBUG] 2020-05-12 08:47:30,708 @ qz.auth.Certificate:?
        Using trusted root certificate: CN=qzindustries.com, O=QZ Industries, LLC (8ef2c0b2fe3f75754245b3fb9d54c0caa1b46bb3)
[INFO] 2020-05-12 08:47:30,713 @ qz.auth.CRL:?
        Loading CRL from https://crl.qz.io
[DEBUG] 2020-05-12 08:47:30,731 @ qz.utils.FileUtilities:?
        Checking for .autostart preference in user directory C:\Users\xx\AppData\Roaming\qz...
[DEBUG] 2020-05-12 08:47:30,732 @ qz.utils.FileUtilities:?
        Checking for .autostart preference in shared directory C:\ProgramData\qz...
[DEBUG] 2020-05-12 08:47:30,749 @ qz.utils.ConnectionUtilities:?
        User agent string for URL requests: Mozilla/5.0 (Windows NT 10.0; WOW64) QZTray/2.1.0 Java/1.8
[INFO] 2020-05-12 08:47:30,861 @ qz.auth.CRL:?
        Successfully loaded 2 CRL entries from https://crl.qz.io
[DEBUG] 2020-05-12 08:47:31,130 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8283
[DEBUG] 2020-05-12 08:47:31,188 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8384
[DEBUG] 2020-05-12 08:47:31,199 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8485
[TRACE] 2020-05-12 08:47:31,419 @ qz.common.AboutInfo:?
        Found latest version: 2.0.12
[INFO] 2020-05-12 08:47:31,464 @ qz.ws.PrintSocketServer:?
        Server started on port(s) 8182, 8181
[INFO] 2020-05-12 08:48:29,932 @ qz.installer.certificate.CertificateManager:?
        SSL certificate is still valid for 809 more days: Sat Jul 30 14:04:53 CEST 2022.  We'll make a new one automatically when needed.
```

**Comment by tresf** [comment]
We're probably expecting the x509 cert header and footer.  Can you try mimicking our format and see if it fixes it?

**Comment by thbl** [comment]
@tresf yea seams to be a bug in cert, tried to fill in a new one and that works.
Think i was missing some of the optional fields.

Btw are you planing for some kind of buying option for 1 licens / site ? (instead of the 400usd company option)

**Comment by tresf** [comment]
> are you planing for some kind of buying option for 1 licens / site ? (instead of the 400usd company option)

We'd be happy to discuss price at sales@qz.io we always work something out that's mutually beneficial!
