### ISSUE TITLE
Fallback to default system printer

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#65]
* When querying for a printer, if it is not found, 2.0 throws an exception and does not print.

```js
 qz.websocket.connect().then(function() { 
  return qz.printers.find("Test")
}).then(function(printer) {
  var config = qz.configs.create(printer);
  var data = [{ type: 'pdf', data: 'assets/pdf_sample.pdf' }];
  return qz.print(config, data);
}).catch(function(e) { console.error(e); });
```

**Stacktrace**
```
[DEBUG] 2016-06-06 21:56:26,841 @ qz.ws.PrintSocketClient:?
	Message: {"call":"printers.find","promise":{},"params":{"query":"Test"},"timestamp":1465264586832,"uid":"z5ovyp"}
[INFO] 2016-06-06 21:56:27,673 @ qz.common.TrayManager:?
	Allowed An anonymous request to access connected printers
[DEBUG] 2016-06-06 21:56:27,676 @ qz.printer.PrintServiceMatcher:?
	Searching for PrintService matching Test
[DEBUG] 2016-06-06 21:56:27,678 @ qz.printer.PrintServiceMatcher:?
	Found 8 printers
[WARN] 2016-06-06 21:56:27,681 @ qz.printer.PrintServiceMatcher:?
	Printer not found: test
```

* If the printer name is hard coded in the `config`, it errors out and does not print anything.
```js
var config = qz.configs.create('Test2');
```

**Stacktrace**
```
[INFO] 2016-06-06 22:05:39,119 @ qz.common.TrayManager:?
	Allowed An anonymous request to connect to QZ
[DEBUG] 2016-06-06 22:05:40,361 @ qz.ws.PrintSocketClient:?
	Message: {"call":"print","promise":{},"params":{"printer":{"name":"Test2"},"options":{"colorType":"color","copies":1,"jobName":null,"density":0,"duplex":false,"interpolation":"bicubic","margins":0,"orientation":null,"paperThickness":null,"printerTray":null,"rotation":0,"scaleContent":true,"size":null,"units":"in","altPrinting":false,"encoding":null,"endOfDoc":null,"perSpool":1},"data":[{"type":"pdf","data":"http://localhost/qz-tray-2.0/demo/assets/pdf_sample.pdf"}]},"timestamp":1465265140350,"uid":"l8g4pe"}
[INFO] 2016-06-06 22:05:42,245 @ qz.common.TrayManager:?
	Allowed An anonymous request to print to Test2
[TRACE] 2016-06-06 22:05:42,247 @ qz.utils.PrintingUtilities:?
	Waiting for processor, 0/1 already in use
[DEBUG] 2016-06-06 22:05:42,249 @ qz.ws.PrintSocketClient:?
	Using qz.printer.action.PrintPDF to print
[DEBUG] 2016-06-06 22:05:42,251 @ qz.printer.PrintServiceMatcher:?
	Searching for PrintService matching Test2
[DEBUG] 2016-06-06 22:05:42,257 @ qz.printer.PrintServiceMatcher:?
	Found 8 printers
[WARN] 2016-06-06 22:05:42,258 @ qz.printer.PrintServiceMatcher:?
	Printer not found: test2
[ERROR] 2016-06-06 22:05:42,260 @ qz.ws.PrintSocketClient:?
	Failed to print
java.lang.IllegalArgumentException: Cannot find printer with name "Test2"
	at qz.printer.PrintOutput.<init>(Unknown Source)
	at qz.ws.PrintSocketClient.processPrintRequest(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)
[TRACE] 2016-06-06 22:05:42,283 @ qz.utils.PrintingUtilities:?
	Returning processor back to pool
```

In both scenarios, should QZ Tray fallback on the default printer on the system and print?

**Comment by tresf** [comment]
> In both scenarios, should QZ Tray fallback on the default printer on the system and print?

In neither scenario should it fallback to the default printer, instead it should `reject` the Promise.  @bberenz thoughts?

**Comment by bberenz** [comment]
I agree that it should just fail the promise. 
Which it looks like it's already doing.

**Comment by tresf** [comment]
> Which it looks like it's already doing.

Ok.  Once @klabarge confirms, we should be able to close this out.

**Comment by klabarge** [comment]
> Ok. Once @klabarge confirms, we should be able to close this out.

It does fail the promise in both scenarios.
