### ISSUE TITLE
2.1.1  Raw Printing  Html  NullPointerException

### ISSUE THREAD

**Issue by showzhou1** [qzind/tray#672]
![image](https://user-images.githubusercontent.com/50538586/84646800-39702600-af35-11ea-962d-25dfbe6a7d64.png)

**Available before version 2.1.0+2，Now I want to upgrade to print html，Then report this error**

![image](https://user-images.githubusercontent.com/50538586/84647322-d92db400-af35-11ea-993f-add2679f50ec.png)

**Attach JDK version**
![image](https://user-images.githubusercontent.com/50538586/84648115-10e92b80-af37-11ea-8dfd-a26372c0bf41.png)

**Attach QZ version**
![image](https://user-images.githubusercontent.com/50538586/84648166-324a1780-af37-11ea-819e-d5fad5a7e9ef.png)

**Comment by tresf** [comment]
@showzhou1 sorry about this issue.  Can you please capture the output from command prompt?  https://qz.io/wiki/faq#console-logs.   As much of the logs as you feel comfortable sharing.  If needed, you may email them to support@qz.io.

**Comment by showzhou1** [comment]
thank you for your reply,
I have sent the complete **debug.log** file to email [support@qz.io](support@qz.io)

**Comment by lite1979** [comment]
Thanks for the logs @showzhou1 

Using the latest QZ-Tray sample.html and QZ-Tray 2.1.1, I was able to reproduce this error.

It appears that "Set to Host" is not working correctly in the latest version of the software.

**Comment by tresf** [comment]
It appears the printer resolution code is breaking this:

```
java.lang.NullPointerException
	at qz.printer.PrintOptions.<init>(PrintOptions.java:116)
	at qz.utils.PrintingUtilities.processPrintRequest(PrintingUtilities.java:148)
	at qz.ws.PrintSocketClient.processMessage(PrintSocketClient.java:348)
	at qz.ws.PrintSocketClient.onMessage(PrintSocketClient.java:235)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:227)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Specifically the call to:
https://github.com/qzind/tray/blob/439c7bc4ef77bb9f3b717bc934e1d51bd4c50bfc/src/qz/printer/PrintOptions.java#L116

**Comment by tresf** [comment]
QZ Tray 2.1.1+1 has been released with this patch.  https://qz.io/download#2.1
