### ISSUE TITLE
Windows uninstall fails as System user

### ISSUE THREAD

**Issue by tresf** [qzind/tray#717]
Steps:

1. Install QZ Tray
1. Install [`psexec`](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec)
1. Open `cmd` As Administrator and run the following command
   ```cmd
   psexec -i -s "%programfiles%\QZ Tray\uninstall.exe"
   ```

Observe the uninstall fails:

```
Running uninstall: "C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe" -Xms512m -Djna.nosys=true -jar "C:\Program Files\QZ Tray\qz-tray.jar" uninstall
[INFO] 2020-09-24 11:14:14,909 @ qz.installer.Installer:?
        Stopping running instances...
[DEBUG] 2020-09-24 11:14:14,909 @ qz.utils.ShellUtilities:?
        Executing: [wmic.exe, process, where, (Name='java.exe' OR Name='javaw.exe'), get, processid]
[DEBUG] 2020-09-24 11:14:15,174 @ qz.utils.ShellUtilities:?
        Executing: [wmic.exe, process, where, CommandLine like '%qz-tray.jar%', get, processid]
[DEBUG] 2020-09-24 11:14:15,455 @ qz.utils.ShellUtilities:?
        Executing: [taskkill.exe, /F, /PID, 5348]
[DEBUG] 2020-09-24 11:14:15,549 @ qz.utils.ShellUtilities:?
        Executing: [jcmd, -l]
[INFO] 2020-09-24 11:14:15,859 @ qz.installer.Installer:?
        Uninstalling from C:\Program Files\QZ Tray
[INFO] 2020-09-24 11:14:15,905 @ qz.installer.Installer:?
        Deleted shared directory: C:\ProgramData\qz
[ERROR] 2020-09-24 11:14:15,937 @ qz.utils.ArgParser:?
        Installation step UNINSTALL failed
com.sun.jna.platform.win32.Win32Exception: The system cannot find the path specified.
        at com.sun.jna.platform.win32.Shell32Util.getKnownFolderPath(Shell32Util.java:93)
        at qz.installer.WindowsSpecialFolders.getPath(Unknown Source)
        at qz.installer.WindowsSpecialFolders.toString(Unknown Source)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at qz.installer.WindowsInstaller.removeSystemSettings(Unknown Source)
        at qz.installer.Installer.uninstall(Unknown Source)
        at qz.utils.ArgParser.processInstallerArgs(Unknown Source)
        at qz.utils.ArgParser.intercept(Unknown Source)
        at qz.ws.PrintSocketServer.main(Unknown Source)
Uninstall failed.
```

---

Note: This issue was previously reported in #713 but split into a separate issue.

**Comment by tresf** [comment]
@AbuHadjar can you please test this installer? https://github.com/tresf/tray/releases/download/v2.1.3-RC/qz-tray-2.1.2+6.exe

**Comment by AbuHadjar** [comment]
@tresf now it looks like it works in 100%. Thanks.
