### ISSUE TITLE
Uninstall fails in headless environment

### ISSUE THREAD

**Issue by tresf** [qzind/tray#776]
```
[ERROR] 2021-03-25 18:57:27,438 @ qz.utils.ArgParser:?
	Installation step uninstall failed
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.desktop/java.awt.Window.<init>(Window.java:548)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/java.awt.Frame.<init>(Frame.java:388)
	at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
	at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
	at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1689)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:868)
	at java.desktop/javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:799)
	at java.desktop/javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:761)
	at java.desktop/javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:722)
	at java.desktop/javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:693)
	at qz.installer.certificate.LinuxCertificateInstaller.promptCertutil(Unknown Source)
	at qz.installer.certificate.LinuxCertificateInstaller.findCertutil(Unknown Source)
	at qz.installer.certificate.LinuxCertificateInstaller.<init>(Unknown Source)
	at qz.installer.certificate.NativeCertificateInstaller.getInstance(Unknown Source)
	at qz.installer.certificate.NativeCertificateInstaller.getInstance(Unknown Source)
	at qz.installer.Installer.removeCerts(Unknown Source)
	at qz.installer.Installer.uninstall(Unknown Source)
	at qz.utils.ArgParser.processInstallerArgs(Unknown Source)
	at qz.utils.ArgParser.intercept(Unknown Source)
	at qz.ws.PrintSocketServer.main(Unknown Source)
```

**Comment by tresf** [comment]
I was hoping catching `HeadlessException` (https://github.com/qzind/tray/commit/b1ac4bb2b09946b8741640253618441fe22ec86a) would catch this, but `AWTError` (extends `Error`, not `Exception`) can still be thrown in certain scenarios, so we'll swallow everything per https://github.com/qzind/tray/commit/271c2090c9aac8c234535b75559d5df43048aad4.
