### ISSUE TITLE
Launch issue on MacOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by juliendemoutiez** [qzind/tray#785]
Hi !!

**Problem**

I've installed QZ Tray 2.1.2 on MacOS Big Sur 11.2.3

When trying to launch the app, the icon on the top bar stays red (I'm having the same issue on Catalina)

Here is the log:

> [ERROR] 2021-04-06 21:50:42,063 @ qz.ws.PrintSocketServer:?
	Could not start tray manager
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1368)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1343)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1479)
	at qz.ws.PrintSocketServer.main(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.awt.Font.getAttributes()" because the return value of "qz.ui.component.LinkLabel.getFont()" is null
	at qz.ui.component.LinkLabel.initialize(Unknown Source)
	at qz.ui.component.LinkLabel.<init>(Unknown Source)
	at qz.ui.GatewayDialog.initComponents(Unknown Source)
	at qz.ui.GatewayDialog.<init>(Unknown Source)
	at qz.common.TrayManager.<init>(Unknown Source)
	at qz.ws.PrintSocketServer.lambda$main$0(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:306)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[WARN] 2021-04-06 21:50:42,065 @ qz.ws.PrintSocketServer:?
	The web socket server is no longer running

Could you please help me figuring out what's wrong ?

Thanks a lot !!

**Comment by tresf** [comment]
Where did you get your Java from? Azul?  I had a similar issue with their Java 16, it's broken.

At time of writing this, the only version we support is AdoptOpenJDK 11. https://adoptopenjdk.net/

If you're on a newer M1 Mac, this does mean you will need to run it through Rosetta 2.  Sorry about this, Java is not yet ready for M1 but we're working very hard with our Java partners to fix that (See also #591)

**Comment by tresf** [comment]
> If you're on a newer M1 Mac, this does mean you will need to run it through Rosetta 2. Sorry about this, Java is not yet ready for M1 but we're working very hard with our Java partners to fix that (See also #591)

To that point, we're about 80% there to get M1 support, I'd be happy to share an M1-compatible beta version so as long as you don't require HTML, Serial or HID support (PDF, Image and Raw printing work just fine).

**Comment by juliendemoutiez** [comment]
Hi,
Downgrading AdoptOpenJDK to v11 fixed it, thanks a lot !!

**Comment by tresf** [comment]
Can you help provide which Java was installed previously?

We test against Java 16 on occasion, the bug I believe is caused by a bad build amd we can reach out to the vendor to let them know.  The bug indicates something is really wrong with Java's Swing interface and it should be properly reported to prevent others from experiencing the same crashes.
