### ISSUE TITLE
DateTimeParseException: Text 'Not Provided' could not be parsed at index 0

### ISSUE THREAD

**Issue by tresf** [qzind/tray#786]
We're not sure how to reproduce, but this was discovered in the logs from our mailing list:

```
java.time.format.DateTimeParseException: Text 'Not Provided' could not be parsed at index 0
    at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
    at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1874)
    at qz.auth.Certificate.loadCertificate(Unknown Source)
    at qz.ui.SiteManagerDialog.readCertificates(Unknown Source)
    at qz.ui.SiteManagerDialog.run(Unknown Source)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by tresf** [comment]
Seems to be introduced by https://github.com/qzind/tray/pull/478.  Investigating...

**Comment by tresf** [comment]
Seems to be benign.  Reduced log severity via 28e376f.
