### ISSUE TITLE
Failed to bind /0.0.0.0:8181

### ISSUE THREAD

**Issue by tresf** [qzind/tray#810]
A user reports that the POS software syndata also binds to 8181, preventing QZ Tray from working.

QZ Tray should fallback to 8282 in this scenario, but it does not appear to be working, or at least it closes itself down before it can.

To reproduce, create a new PowerShell:

1. Run PowerShell as Administrator
    ```ps1
    Set-Executionpolicy RemoteSigned
    ```

2.  Run PowerShell ISE as a regular user
    ```ps1
    $Listener = [System.Net.Sockets.TcpListener]8181;
    $Listener.Start();
    ```

3. Start QZ Tray

![WhatsApp Image 2021-05-07 at 14 36 50](https://user-images.githubusercontent.com/6345473/117500063-19c95e00-af4a-11eb-84b3-0df33b152655.jpeg)

**Comment by tresf** [comment]
Attaching logs:

```
java.io.IOException: Failed to bind to /0.0.0.0:8181
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at qz.ws.PrintSocketServer.runServer(Unknown Source)
        at qz.ws.PrintSocketServer.main(Unknown Source)
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
        ... 8 more
[DEBUG] 2021-05-07 16:47:51,468 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8182
```

@bberenz what's odd is it seems like it's detecting and closing itself.  I assume some off-by one scenario?

**Comment by tresf** [comment]
This was pretty hard to test on macOS due to some very odd behavior with the ports, documented here: https://github.com/eclipse/jetty.project/issues/6266.

Windows behaves as expected though, added a unit-test in the original bug description.

**Comment by tresf** [comment]
Unrelated, but similar symptom: #816
