### ISSUE TITLE
MacOS Big Sur cannot open QZ Tray if OpenJDK16 is installed

### ISSUE THREAD

**Issue by MikeGlennFWC** [qzind/tray#822]
Hi,

I have to have OpenJDK16 installed, because it's installed as a dependency for a few other things.

I also have AdaptOpenJDK11 installed, setting the JAVA_HOME environment variable doesn't seem to work, QZ Tray ignores it.

When i run ./QZ\ Tray from the app bundle, it runs the command `java_home -v 1.8+` and the plus appears to just seek out the latest version of Java installed, maybe there is a way to skip the java_home command from running, but i cannot figure it out?

I've checked a number of other issues and can't seem to find anyone with the same problem.

Is there a way i can get this running, without removing OpenJDK16?

Thanks

**Comment by tresf** [comment]
Which version of QZ Tray?  QZ Tray 2.1.3 added better support for Big Sur as well as initial support for JDK16 on Intel and ARM.  I would expect QZ Tray to work with JDK16, but if you're on the ARM version, some features would be unavailable such as serial, HID and HTML.

**Comment by MikeGlennFWC** [comment]
Interesting,

QZ version 2.1.3, i downloaded it this morning, i just get the tray icon (red) and it doesn't respond to anything, the qz.io demo doesn't connect to it. what i describe above is when i try to run it manually from the command line..

Here is a snapshot of some of the first errors (theres a hell of a lot)

> In initComponentDefaults
[INFO] 2021-06-09 21:19:41,034 @ qz.auth.CRL:?
	Successfully loaded 4 CRL entries from https://crl.qz.io
java.lang.Error: no ComponentUI class for: javax.swing.JPanel[,0,0,0x0,invalid,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:762)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:144)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:792)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1069)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
	at java.desktop/javax.swing.JRootPane.createGlassPane(JRootPane.java:517)
	at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:344)
	at java.desktop/javax.swing.JDialog.createRootPane(JDialog.java:670)
	at java.desktop/javax.swing.JDialog.dialogInit(JDialog.java:649)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:280)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:207)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:180)
	at org.jdesktop.swinghelper.tray.JXTrayIcon.<clinit>(Unknown Source)
	at qz.ui.tray.TrayType.init(Unknown Source)
	at qz.ui.tray.TrayType.init(Unknown Source)
	at qz.common.TrayManager.<init>(Unknown Source)
	at qz.ws.PrintSocketServer.lambda$main$0(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:306)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.Error: no ComponentUI class for: javax.swing.JPanel[,0,0,0x0,invalid,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:762)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:144)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:792)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1069)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
	at java.desktop/javax.swing.JRootPane.createContentPane(JRootPane.java:492)
	at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:346)
	at java.desktop/javax.swing.JDialog.createRootPane(JDialog.java:670)
	at java.desktop/javax.swing.JDialog.dialogInit(JDialog.java:649)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:280)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:207)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:180)
	at org.jdesktop.swinghelper.tray.JXTrayIcon.<clinit>(Unknown Source)
	at qz.ui.tray.TrayType.init(Unknown Source)
	at qz.ui.tray.TrayType.init(Unknown Source)
	at qz.common.TrayManager.<init>(Unknown Source)
	at qz.ws.PrintSocketServer.lambda$main$0(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:306)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.Error: no ComponentUI class for: javax.swing.JRootPane[,0,0,0x0,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=1,maximumSize=,minimumSize=,preferredSize=]

**Comment by tresf** [comment]
It's because you have a broken JDK.  I think Zulu's 16 is broken.  Which are you using?  We helped write the Homebrew version and it should wkeky, if that's an option.

Your error should be able to reproduce with any Java app that uses Swing libraries and is most likely unrelated to QZ Tray specifically.

**Comment by MikeGlennFWC** [comment]
I can't see any reference to Zulu in the brew file.

from `brew info`

```
openjdk: stable 16.0.1 (bottled) [keg-only]
Development kit for the Java programming language
https://openjdk.java.net/
/usr/local/Cellar/openjdk/16.0.1 (617 files, 330MB)
  Poured from bottle on 2021-05-31 at 18:29:05
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openjdk.rb
License: GPL-2.0-only with Classpath-exception-2.0
```

from `java -version`
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Homebrew (build 16.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 16.0.1+0, mixed mode, sharing)
```

p.s, thank you for the quick responses.

**Comment by MikeGlennFWC** [comment]
I forgot to mention, i'm not using an M1 (ARM) Mac, i'm using Intel.

**Comment by tresf** [comment]
Sorry to suggest `brew` uses Zulu, it does not, however there are some issues with Java 16 out there on the wild and when we tested Zulu 16 we had identical errors. They were not present with Zulu 15.

I wasn't aware of issues with Homebrew's 16, but it should be quick to test.

**Comment by tresf** [comment]
So far all openjdk16 builds I've tried on Intel have this same identical issue.  We'll keep investigating.

**Comment by tresf** [comment]
So it turns out the dark mode theme we use is incompatible with OpenJDK16.  Java doesn't ship with dark mode support, so we use a 3rd party theme to do this.

We'll need to investigate further to see if there's an upstream fix.  A temporary workaround is to switch the entire Dekstop to use the light theme.  I understand this is neither ideal nor desired but it seems to fix the crash.

There still may be an underlying bug with OpenJDK16, but identifying this will take more time.

**Comment by tresf** [comment]
Upstream bug report filed here: https://github.com/bobbylight/Darcula/issues/8.  We'll have to see what can be done to detect this bug and circumvent this issue.  Sorry for the trouble.

**Comment by tresf** [comment]
I'll also work towards a workaround which allows another JDK to be forced.

**Comment by MikeGlennFWC** [comment]
Excellent!

i've just switched to light mode and it works. thanks for figuring that out.

**Comment by tresf** [comment]
@MikeGlennFWC thanks for the bug report.  This whole time we thought the Java 16 VMs were broken, but it's a compatibility issue with our theme.  We'll find a way to disable this and get a patch out as soon as possible.

**Comment by tresf** [comment]
@MikeGlennFWC can you please test this [updated installer](https://github.com/tresf/tray/releases/download/v2.1.4-RC/qz-tray-2.1.3+1.pkg)?

We'll need to do some regression testing before publishing, but it should simply disable dark mode on Java 16 to circumvent the bug while we await a more permanent fix.

**Comment by MikeGlennFWC** [comment]
Ok, i've removed QZ Tray, switched back to dark mode, installed the package you linked and it's working fine now.

Thanks

**Comment by klabarge** [comment]
>We'll need to do some regression testing before publishing

I tested this installer against AdoptOpenJDK version 8, 11, and 16 and experienced no regressions. I purged Java in between installations and launched QZ Tray in both light and dark mode.

**Comment by tresf** [comment]
Thanks @klabarge.  A patched installer available at https://qz.io/download.   New issue to track the re-enabling of this dark mode theme is here: #824
