### ISSUE TITLE
facing error while activating ssl on qz.tray 2.0.12

### ISSUE THREAD

**Issue by jubin006** [qzind/tray#827]
```bash
C:\Users\TecStub\Desktop>cscript "%PROGRAMFILES%\QZ Tray\auth\windows-keygen.js" "%PROGRAMFILES%\QZ Tray" install "" "" "fullchain.pem" "privkey.pem"
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

Creating PKCS12 keypair (this requires openssl)...
 - [failed] Creating PKCS12 keypair
ERROR: Error creating PKCS12 keypair from: fullchain.pem, privkey.pem to C:\Program Files\QZ Tray\auth\qz-tray.p12
```

**Comment by jubin006** [comment]
Hi Team,

Can plz help me how to install https ssl certificate on qz tray 2.0.12. I am trying to install it but getting error, 

C:\Users\TecStub\Desktop>java -jar "%PROGRAMFILES%\QZ Tray\qz-tray.jar" certgen --key "privkey.pem" --cert "fullchain.pem"
[INFO] 2021-06-23 11:41:58,885 @ qz.ws.PrintSocketServer:?
        QZ Tray version: 2.0.12
[INFO] 2021-06-23 11:41:58,887 @ qz.ws.PrintSocketServer:?
        QZ Tray vendor: QZ Industries, LLC
[INFO] 2021-06-23 11:41:58,887 @ qz.ws.PrintSocketServer:?
        Java version: 1.8.0+291
[INFO] 2021-06-23 11:41:58,887 @ qz.ws.PrintSocketServer:?
        Java vendor: Oracle Corporation
[DEBUG] 2021-06-23 11:41:58,958 @ qz.utils.ShellUtilities:?
        Executing: [C:\Windows\system32\reg.exe, query, HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize, /v, AppsUseLightTheme]
[DEBUG] 2021-06-23 11:41:59,275 @ qz.utils.ShellUtilities:?
        Executing: [C:\Windows\system32\reg.exe, query, HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1, /v, Flags]
[DEBUG] 2021-06-23 11:41:59,299 @ qz.utils.ShellUtilities:?
        Executing: [C:\Windows\system32\reg.exe, query, HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\ExperimentalFeatures, /v, AllowLocalhostLoopback]
[INFO] 2021-06-23 11:41:59,472 @ qz.deploy.DeployUtilities:?
        Main properties file C:\Program Files\QZ Tray\qz-tray.properties
[DEBUG] 2021-06-23 11:41:59,514 @ qz.auth.Certificate:?
        Using trusted root certificate: CN=qzindustries.com, O=QZ Industries, LLC (8ef2c0b2fe3f75754245b3fb9d54c0caa1b46bb3)
[INFO] 2021-06-23 11:41:59,514 @ qz.auth.CRL:?
        Loading CRL from https://crl.qz.io
[DEBUG] 2021-06-23 11:41:59,608 @ qz.utils.ShellUtilities:?
        Executing: [C:\Windows\system32\reg.exe, query, HKCU\Software\Microsoft\Windows\CurrentVersion\Run\, /v, QZ Tray]
[WARN] 2021-06-23 11:42:00,149 @ org.eclipse.jetty.util.component.AbstractLifeCycle:212
        FAILED ServerConnector@1ec1f0c{HTTP/1.1}{0.0.0.0:8182}: java.net.BindException: Address already in use: bind
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at qz.ws.PrintSocketServer.runServer(Unknown Source)
        at qz.ws.PrintSocketServer.main(Unknown Source)
[WARN] 2021-06-23 11:42:00,151 @ org.eclipse.jetty.util.component.AbstractLifeCycle:212
        FAILED ServerConnector@12b07fd{SSL-HTTP/1.1}{0.0.0.0:8181}: java.net.BindException: Address already in use: bind
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at qz.ws.PrintSocketServer.runServer(Unknown Source)
        at qz.ws.PrintSocketServer.main(Unknown Source)
[WARN] 2021-06-23 11:42:00,153 @ org.eclipse.jetty.util.component.AbstractLifeCycle:212
        FAILED org.eclipse.jetty.server.Server@bf3bbf: MultiException[java.net.BindException: Address already in use: bind, java.net.BindException: Address already in use: bind]
MultiException[java.net.BindException: Address already in use: bind, java.net.BindException: Address already in use: bind]
        at org.eclipse.jetty.server.Server.doStart(Server.java:329)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at qz.ws.PrintSocketServer.runServer(Unknown Source)
        at qz.ws.PrintSocketServer.main(Unknown Source)
        Suppressed: java.net.BindException: Address already in use: bind
                at sun.nio.ch.Net.bind0(Native Method)
                at sun.nio.ch.Net.bind(Unknown Source)
                at sun.nio.ch.Net.bind(Unknown Source)
                at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
                at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
                at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
                at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
                at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.server.Server.doStart(Server.java:366)
                ... 3 more
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        ... 3 more
[DEBUG] 2021-06-23 11:42:00,174 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8182
[DEBUG] 2021-06-23 11:42:00,199 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8384
[DEBUG] 2021-06-23 11:42:00,203 @ qz.ws.SingleInstanceChecker:?
        Checking for a running instance of QZ Tray on port 8485
[INFO] 2021-06-23 11:42:00,211 @ qz.ws.PrintSocketServer:?
        Server started on port(s) 8283, 8282
[WARN] 2021-06-23 11:42:00,240 @ qz.ws.SingleInstanceChecker:?
        Connection closed, null
[WARN] 2021-06-23 11:42:00,240 @ qz.ws.SingleInstanceChecker:?
        QZ Tray is already running on localhost/127.0.0.1:8182
[WARN] 2021-06-23 11:42:00,248 @ qz.ws.PrintSocketServer:?
        The web socket server is no longer running
[INFO] 2021-06-23 11:42:00,312 @ qz.auth.CRL:?
        Successfully loaded 4 CRL entries from https://crl.qz.io
[WARN] 2021-06-23 11:42:03,253 @ org.eclipse.jetty.util.thread.QueuedThreadPool:178
        WebSocketClient@22244729{STOPPING,8<=8<=200,i=0,q=1} Couldn't stop Thread[WebSocketClient@22244729-51,5,main]
If you have installation steps documents with you for windows please share with me

**Comment by tresf** [comment]
> If you have installation steps documents with you for windows please share with me

The instructions are for 2.1.3.  They will not work on 2.0.12.

**Comment by tresf** [comment]
Please install QZ Tray 2.1 and follow the following steps: https://qz.io/wiki/print-server#remove-localhost-bindings

If you require QZ Tray 2.0, the 2.0 instructions are available on this tutorial as well, but require `openssl` is available as a command on your machine, which must be downloaded, installed and placed on your path as a separate step.
