### ISSUE TITLE
Could not send message java.util.zip.ZipException

### ISSUE THREAD

**Issue by tresf** [qzind/tray#843]
Quoting https://github.com/qzind/tray/issues/839#issue-948860360.

> I am running Linux mint v20 ulyana, This is Ubuntu focal
> Java version and where I got it from
> ```
> https://adoptopenjdk.jfrog.io/adoptopenjdk/deb focal/main amd64 adoptopenjdk-8-hotspot-jre amd64 8u292-b10-3 [41.5 MB]
> adoptopenjdk-8-hotspot-jre (8u292-b10-3) from (apt install adoptopenjdk-8-hotspot-jre)
> ```

```
2021-07-24 23:46:28,326 [ERROR] Could not send message
java.util.zip.ZipException
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.outgoingFrame(CompressExtension.java:236)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process(ExtensionStack.java:400)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame(ExtensionStack.java:277)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:306)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.blockingWrite(WebSocketRemoteEndpoint.java:106)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendString(WebSocketRemoteEndpoint.java:384)
	at qz.ws.PrintSocketClient.send(Unknown Source)
	at qz.ws.PrintSocketClient.sendResult(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:227)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

FYI @frankmasio

**Comment by tresf** [comment]
I tested the Ubuntu 20.04 ARM64 version with `openjdk-8-jdk` and the issue is not reproducible.  Testing next on Intel with the AdoptOpenJDK release.

**Comment by tresf** [comment]
I'm testing on Ubuntu 20.04 Intel version with `adoptopenjdk-8-hotspot` and it won't even install.  I receive the following:

```diff
  ubuntu@ubuntu:~$ sudo bash '/home/ubuntu/Downloads/qz-tray-2.1.3.run' 
  Verifying archive integrity...  100%   MD5 checksums are OK. All good.
  Uncompressing QZ Tray Installer  100%  
  Starting install...

  Running preinstall task...
+       [success] Task preinstall was successful
  Running install task...
+       [success] Task install was successful
  Running certgen task...
-       [failure] Task certgen failed.
```

... which is a duplicate of #814 and is caused by an upstream regression caused by OpenJDK8.  A workaround for this is to use OpenJDK11, or use an installer which contains a workaround for this bug.

... However, even if I install using openjdk11 and then run with openjdk8, I can't reproduce the original issue.  @frankmasio are you experiencing this?  Does the issue still occur with openjdk11?

Note, I'm testing with Ubuntu 20.04, not Mint, so there could be slight differences.

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

**Comment by tresf** [comment]
Closing, I think this issue was related to OpenJDK8 and isn't really a problem for most users since we bundle OpenJDK11. 
 Please feel free to comment on this or request reopen if warranted.
