### ISSUE TITLE
Error when I try to compile for mac

### ISSUE THREAD

**Issue by zaqueoae** [qzind/tray#846]
I have compiled Qz for linux and for Windows without problem. However when I try to compile for mac it gives me an error.
Says "File or directory does not exist"
I am doing this from an ubuntu terminal

```
BUILD FAILED
/media/donquijote/7da1693b-6827-481b-8675-073d723a6fa0/tray/ant/apple/installer.xml:83: Execute failed: java.io.IOException: Cannot run program "pkgbuild" (in directory "/media/donquijote/7da1693b-6827-481b-8675-073d723a6fa0/tray"): error=2, No existe el archivo o el directorio
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:630)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:497)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: error=2, No existe el archivo o el directorio
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 24 more

Total time: 18 seconds
```

**Comment by tresf** [comment]
`pkgbuild` is offered as a command-line tool for MacOS.  Once you install that, you should be fine.  `sudo xcode-select --install` may do the trick. If not, please install XCode from the AppStore.

**Comment by tresf** [comment]
> I am doing this from an ubuntu terminal

Oh, we don't support this yet.  You can try to use Darling, your mileage may vary.  Apple's tools are quite proprietary still.  If you can get Darling working, please share your success.

**Comment by zaqueoae** [comment]
Thanks a lot. I am going to study everything you have told me. I will return commenting on the result.

**Comment by tresf** [comment]
So, I tried this... I got pretty far, but in the end I failed.... Here are my notes... 

1. Install all [dependencies](https://docs.darlinghq.org/build-instructions.html) as well as [`git-lfs`](https://github.com/darlinghq/darling/issues/861#issuecomment-904691580)
1. Make sure to install `git-lfs` using the command `git lfs install`.
1. [Clone, compile and install](https://docs.darlinghq.org/build-instructions.html#fetch-the-sources) `darling`
1. If needed (e.g. Ubuntu), [patch the kernel module](https://github.com/darlinghq/darling/issues/1012#issuecomment-904327908), compile and install [`lkm`](https://docs.darlinghq.org/build-instructions.html#building-and-installing)
1. Download and [extract](https://github.com/darlinghq/darling#working-with-xip-archives) XCode using `unxip` command
1. If `xcode-select --install` isn't working, [manually download, mount and install the matching Command Line Tools](https://github.com/darlinghq/darling/issues/1006#issuecomment-904339864) for XCode

Unfortunately, I still [get errors just trying basic command-line options (e.g. `git`)](https://gist.github.com/tresf/18e8d8f033eb0aeca55b988851a45328) and I'm having a hard time finding out any one tutorial that warns of compatibility with certain Linux OS versions, XCode versions, Command Line utilities, etc making this process nearly impossible to support.

If you get further, feel free to request a reopen. 🍻
