### ISSUE TITLE
Startup error with custom SSL certificate

### ISSUE THREAD

**Issue by tresf** [qzind/tray#887]
Steps to reproduce:

(openjdk 11.0.8, preinstalled with Raspberry Pi OS)

1. Obtain a LetsEncrypt SSL certificate
2. Reinstall QZ Tray using the SSL cert/key from LetsEncrypt using the print-server steps
3. Start QZ Tray with the newly installed SSL certificate

```
org.bouncycastle.util.io.pem.PemGenerationException: encoding exception: unknown object passed - can't encode.
	at org.bouncycastle.openssl.MiscPEMGenerator.generate(Unknown Source)
	at qz.installer.certificate.CertificateManager.writeCert(Unknown Source)
	at qz.installer.Installer.certGen(Unknown Source)
	at qz.ws.PrintSocketServer.main(Unknown Source)
Caused by: org.bouncycastle.util.io.pem.PemGenerationException: unknown object passed - can't encode.
	at org.bouncycastle.openssl.MiscPEMGenerator.createPemObject(Unknown Source)
	... 4 more
```

**Comment by tresf** [comment]
This issue seems to be benign, just makes the startup logs hard to check for errors.
