### ISSUE TITLE
Issue Print Service is no longer available

### ISSUE THREAD

**Issue by amitinvizio** [qzind/tray#903]
I am getting this issue while printing the text file raw command
2021-12-27T16:02:04,982 [ERROR] Failed to print
javax.print.PrintException: PrintService is no longer available.
	at sun.print.Win32PrintJob.print(Win32PrintJob.java:318) ~[?:?]
	at qz.printer.action.PrintRaw.waitForPrint(Unknown Source) ~[qz-tray.jar:?]
	at qz.printer.action.PrintRaw.printToPrinter(Unknown Source) ~[qz-tray.jar:?]
	at qz.printer.action.PrintRaw.print(Unknown Source) ~[qz-tray.jar:?]
	at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source) [qz-tray.jar:?]
	at qz.ws.PrintSocketClient.processMessage(Unknown Source) [qz-tray.jar:?]
	at qz.ws.PrintSocketClient.onMessage(Unknown Source) [qz-tray.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) [qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68) [qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:227) [qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914) [qz-tray.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by lite1979** [comment]
@amitinvizio 

I'm sorry for the trouble. When we have seen this error in the past, it has been one of three things:

1. Bad printer mapping in the JVM (usually fixed by a normal reboot)
2. Corrupt memory on the disk drive (usually SSD - fixed by issuing `chkdsk /f` in CMD and rebooting)
3. Printspooler issue - best explained by this video:  https://www.youtube.com/watch?v=Jmw_-6F2GwI

Please let us know if you continue to have problems.

**Comment by tresf** [comment]
Yeah, this usually means the printer was removed from the spooler since QZ Tray was started.  We fetch a list of printers at startup and check for new ones periodically, but if the printer was removed, it will say that the `PrintService` is no longer available.

**Comment by tresf** [comment]
Closing since the issue cannot be reproduced.  If you can provide steps to reproduce, please reach out and we'll examine the code involved.
