### ISSUE TITLE
Unable to delete file: C:\Program Files\QZ Tray\runtime\bin\lcms.dll

### ISSUE THREAD

**Issue by tresf** [qzind/tray#907]
Installing QZ Tray 2.2 Intel version on Windows 10 ARM64 when QZ Tray is already running throws the following error.

```
Output folder: C:\Program Files\QZ Tray
Output folder: C:\Users\owner\AppData\Local\Temp\nso798F.tmp\payload
Extracting...
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM (build 11.0.12+7-LTS, mixed mode)
Running preinstall: "C:\Users\owner\AppData\Local\Temp\nso798F.tmp\payload\runtime\bin\java.exe" -Djna.nosys=true -jar "C:\Users\owner\AppData\Local\Temp\nso798F.tmp\payload\qz-tray.jar" "preinstall" "" ""
[INFO] 2022-01-19 22:58:45,500 @ qz.installer.Installer:?
        Fixing runtime permissions...
[INFO] 2022-01-19 22:58:45,502 @ qz.installer.Installer:?
        Stopping running instances...
[DEBUG] 2022-01-19 22:58:45,509 @ qz.utils.ShellUtilities:?
        Executing: [wmic.exe, process, where, (Name='java.exe' OR Name='javaw.exe'), get, processid]
[DEBUG] 2022-01-19 22:58:45,657 @ qz.utils.ShellUtilities:?
        Executing: [wmic.exe, process, where, CommandLine like '%qz-tray.jar%', get, processid]
[DEBUG] 2022-01-19 22:58:45,717 @ qz.utils.ShellUtilities:?
        Executing: [taskkill.exe, /F, /PID, 8740]
Running install: "C:\Users\owner\AppData\Local\Temp\nso798F.tmp\payload\runtime\bin\java.exe" -Djna.nosys=true -jar "C:\Users\owner\AppData\Local\Temp\nso798F.tmp\payload\qz-tray.jar" "install" "--dest" "C:\Program Files\QZ Tray"
[INFO] 2022-01-19 22:58:46,220 @ qz.installer.Installer:?
        Installing to C:\Program Files\QZ Tray
[ERROR] 2022-01-19 22:58:46,251 @ qz.utils.ArgParser:?
        Installation step INSTALL failed
java.io.IOException: Unable to delete file: C:\Program Files\QZ Tray\runtime\bin\lcms.dll
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
        at qz.installer.Installer.deployApp(Unknown Source)
        at qz.installer.Installer.install(Unknown Source)
        at qz.installer.Installer.install(Unknown Source)
        at qz.utils.ArgParser.processInstallerArgs(Unknown Source)
        at qz.utils.ArgParser.intercept(Unknown Source)
        at qz.App.main(Unknown Source)
Installation failed during install step.  Please check log for details.
```

A temporary workaround is to try the install again.

**Comment by tresf** [comment]
The error occured when installing an older 2.2.0-SNAPSHOT version of QZ Tray, of which I have little information on.  I'll close this for now but reopen if it continues to occur with stable releases.
