### ISSUE TITLE
Another NPE caused by missing default printer

### ISSUE THREAD

**Issue by tresf** [qzind/tray#948]
**Version:** QZ Tray 2.1.6+2
**OS:** Raspberry Pi

```
java.lang.NullPointerException: null
      at qz.printer.info.CupsPrinterMap.putAll(Unknown Source) ~[qz-tray.jar:?]
      at qz.printer.PrintServiceMatcher.getDefaultPrinter(Unknown Source) ~[qz-tray.jar:?]
      at qz.printer.PrintServiceMatcher.matchPrinter(Unknown Source) ~[qz-tray.jar:?]
      at qz.printer.PrintServiceMatcher.matchPrinter(Unknown Source) ~[qz-tray.jar:?]
      at qz.printer.PrintOutput.<init>(Unknown Source) ~[qz-tray.jar:?]
      at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source) ~[qz-tray.jar:?]
      at qz.ws.PrintSocketClient.processMessage(Unknown Source) ~[qz-tray.jar:?]
      at qz.ws.PrintSocketClient.onMessage(Unknown Source) ~[qz-tray.jar:?]
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
      at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
      at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) ~[qz-tray.jar:?]
      at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68) ~[qz-tray.jar:?]
      at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.lambda$onTextFrame$1(JettyAnnotatedEventDriver.java:270) ~[qz-tray.jar:?]
      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[qz-tray.jar:?]
      at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[qz-tray.jar:?]
      at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

**Comment by tresf** [comment]
Build available for testing: https://github.com/tresf/tray/releases/download/TEMP/qz-tray-2.1.6+PICRASH.run
