### ISSUE TITLE
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 4  %C:\Users\john%

### ISSUE THREAD

**Issue by tresf** [qzind/tray#968]
Placeholder for a crash during install with the following stacktrace:

2.1:
```
[INFO] 2022-05-02T14:27:10,551 @ qz.installer.WindowsInstaller:-1
        Creating launcher "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\QZ Tray\QZ Tray.lnk" -> "C:\Program Files\QZ Tray\qz-tray.exe"
[ERROR] 2022-05-02T14:27:10,555 @ qz.utils.ArgParser:-1
        Installation step INSTALL failed
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 4
%C:\Users\john%
    ^
        at java.util.regex.Pattern.error(Pattern.java:2028) ~[?:?]
        at java.util.regex.Pattern.escape(Pattern.java:2608) ~[?:?]
        at java.util.regex.Pattern.atom(Pattern.java:2286) ~[?:?]
        at java.util.regex.Pattern.sequence(Pattern.java:2210) ~[?:?]
        at java.util.regex.Pattern.expr(Pattern.java:2069) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1783) ~[?:?]
        at java.util.regex.Pattern.<init>(Pattern.java:1430) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1095) ~[?:?]
        at mslinks.ShellLink.resolveEnvVariables(ShellLink.java:392) ~[qz-tray.jar:?]
        at mslinks.ShellLink.setTarget(ShellLink.java:333) ~[qz-tray.jar:?]
        at mslinks.ShellLink.createLink(ShellLink.java:377) ~[qz-tray.jar:?]
        at mslinks.ShellLink.createLink(ShellLink.java:385) ~[qz-tray.jar:?]
        at qz.installer.WindowsInstaller.addAppLauncher(Unknown Source) ~[qz-tray.jar:?]
        at qz.installer.Installer.install(Unknown Source) ~[qz-tray.jar:?]
        at qz.installer.Installer.install(Unknown Source) ~[qz-tray.jar:?]
        at qz.utils.ArgParser.processInstallerArgs(Unknown Source) ~[qz-tray.jar:?]
        at qz.utils.ArgParser.intercept(Unknown Source) ~[qz-tray.jar:?]
        at qz.ws.PrintSocketServer.main(Unknown Source) ~[qz-tray.jar:?]
Installation failed during install step.  Please check log for details.
```

2.2:
```
[INFO] 2022-05-02T14:28:37,659 @ qz.installer.WindowsInstaller:-1
        Creating launcher "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\QZ Tray\QZ Tray.lnk" -> "C:\Program Files\QZ Tray\qz-tray.exe"
[ERROR] 2022-05-02T14:28:37,663 @ qz.utils.ArgParser:-1
        Installation step INSTALL failed
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 4
%C:\Users\john%
    ^
        at java.util.regex.Pattern.error(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.escape(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.atom(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.sequence(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.expr(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.<init>(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
        at mslinks.ShellLink.resolveEnvVariables(ShellLink.java:392) ~[qz-tray.jar:?]
        at mslinks.ShellLink.setTarget(ShellLink.java:333) ~[qz-tray.jar:?]
        at mslinks.ShellLink.createLink(ShellLink.java:377) ~[qz-tray.jar:?]
        at mslinks.ShellLink.createLink(ShellLink.java:385) ~[qz-tray.jar:?]
        at qz.installer.WindowsInstaller.addAppLauncher(Unknown Source) ~[qz-tray.jar:?]
        at qz.installer.Installer.install(Unknown Source) ~[qz-tray.jar:?]
        at qz.installer.Installer.install(Unknown Source) ~[qz-tray.jar:?]
        at qz.utils.ArgParser.processInstallerArgs(Unknown Source) [qz-tray.jar:?]
        at qz.utils.ArgParser.intercept(Unknown Source) [qz-tray.jar:?]
        at qz.App.main(Unknown Source) [qz-tray.jar:?]
Installation failed during install step.  Please check log for details.
```

**Comment by tresf** [comment]
Seems to be an upstream bug reported here: https://github.com/DmitriiShamrikov/mslinks/issues/26.  Will bump mslinks and have the offending user test it out.

**Comment by tresf** [comment]
Turns out mslinks is no longer available for JDK11, asked about it here: https://github.com/DmitriiShamrikov/mslinks/issues/33.  Will attempt to build my own release while I await the decision of the project.

**Comment by tresf** [comment]
Incase upstream rejects it, the steps to compile for JDK11:

1. Clone the repo
   ```bash
   git clone https://github.com/DmitriiShamrikov/mslinks
   ```
2. If not already, install gradle:
   ```bash
   brew install gradle         # mac
   # -- OR --
   sudo apt-get install gradle # linux
3. Apply this patch https://github.com/DmitriiShamrikov/mslinks/pull/34/commits/9b60ff41a7d63908c47695f85bf37b2f18c6dd4f
4. Build
   ```bash
   gradle build
   ```
5. Copy `mslinks-(version).jar` to `tray/libs`, remote the old version.
