### ISSUE TITLE
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <unknown>

### ISSUE THREAD

**Issue by alu0100990539** [qzind/tray#971]
I following these [tutorial](https://ijustlearnedsomethingnewtoday.blogspot.com/2017/04/using-self-signed-certificates-with-qz.html) and all go good, but when I try to install the new auto-compile .exe, the installation failed, this is te log of the installation prompt:

```
Output folder: C:\Program Files\QZ Tray
Output folder: C:\Users\Usuario\AppData\Local\Temp\nsb9520.tmp\payload
Extracting...
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
Running preinstall: "C:\Users\Usuario\AppData\Local\Temp\nsb9520.tmp\payload\runtime\bin\java.exe" -Djna.nosys=true -jar "C:\Users\Usuario\AppData\Local\Temp\nsb9520.tmp\payload\qz-tray.jar" "preinstall" "" ""
[INFO] 2022-05-07T17:14:41,736 @ qz.installer.Installer:-1
        Fixing runtime permissions...
[INFO] 2022-05-07T17:14:41,744 @ qz.installer.Installer:-1
        Stopping running instances...
[DEBUG] 2022-05-07T17:14:41,751 @ qz.utils.ShellUtilities:-1
        Executing: [wmic.exe, process, where, (Name='java.exe' OR Name='javaw.exe'), get, processid]
[DEBUG] 2022-05-07T17:14:41,936 @ qz.utils.ShellUtilities:-1
        Executing: [wmic.exe, process, where, CommandLine like '%qz-tray.jar%', get, processid]
Running install: "C:\Users\Usuario\AppData\Local\Temp\nsb9520.tmp\payload\runtime\bin\java.exe" -Djna.nosys=true -jar "C:\Users\Usuario\AppData\Local\Temp\nsb9520.tmp\payload\qz-tray.jar" "install" "--dest" "C:\Program Files\QZ Tray"
[INFO] 2022-05-07T17:14:42,778 @ qz.installer.Installer:-1
        Installing to C:\Program Files\QZ Tray
[INFO] 2022-05-07T17:14:44,106 @ qz.installer.WindowsInstaller:-1
        Removing legacy startup entries for all users matching QZ Tray
[INFO] 2022-05-07T17:14:44,158 @ qz.installer.Installer:-1
        Created shared directory: C:\ProgramData\qz
[INFO] 2022-05-07T17:14:44,159 @ qz.installer.WindowsInstaller:-1
        Creating launcher "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\QZ Tray\QZ Tray.lnk" -> "C:\Program Files\QZ Tray\qz-tray.exe"
[WARN] 2022-05-07T17:14:44,169 @ qz.installer.WindowsInstaller:-1
        Could not create launcher
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <unknown>
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:?]
        at java.nio.file.Path.of(Unknown Source) ~[?:?]
        at java.nio.file.Paths.get(Unknown Source) ~[?:?]
        at mslinks.ShellLinkHelper.saveTo(ShellLinkHelper.java:153) ~[qz-tray.jar:?]
        at mslinks.ShellLink.saveTo(ShellLink.java:330) ~[qz-tray.jar:?]
        at mslinks.ShellLink.createLink(ShellLink.java:366) ~[qz-tray.jar:?]
        at qz.installer.WindowsInstaller.addAppLauncher(Unknown Source) ~[qz-tray.jar:?]
        at qz.installer.Installer.install(Unknown Source) ~[qz-tray.jar:?]
        at qz.installer.Installer.install(Unknown Source) ~[qz-tray.jar:?]
        at qz.utils.ArgParser.processInstallerArgs(Unknown Source) ~[qz-tray.jar:?]
        at qz.utils.ArgParser.intercept(Unknown Source) ~[qz-tray.jar:?]
        at qz.App.main(Unknown Source) ~[qz-tray.jar:?]
[INFO] 2022-05-07T17:14:44,178 @ qz.installer.WindowsInstaller:-1
        Creating startup entry "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\QZ Tray.lnk" -> "C:\Program Files\QZ Tray\qz-tray.exe"
[ERROR] 2022-05-07T17:14:44,179 @ qz.utils.ArgParser:-1
        Installation step INSTALL failed
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <unknown>
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:?]
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:?]
        at java.nio.file.Path.of(Unknown Source) ~[?:?]
        at java.nio.file.Paths.get(Unknown Source) ~[?:?]
        at mslinks.ShellLinkHelper.saveTo(ShellLinkHelper.java:153) ~[qz-tray.jar:?]
        at mslinks.ShellLink.saveTo(ShellLink.java:330) ~[qz-tray.jar:?]
        at mslinks.ShellLink.createLink(ShellLink.java:366) ~[qz-tray.jar:?]
        at qz.installer.WindowsInstaller.addStartupEntry(Unknown Source) ~[qz-tray.jar:?]
        at qz.installer.Installer.install(Unknown Source) ~[qz-tray.jar:?]
        at qz.installer.Installer.install(Unknown Source) ~[qz-tray.jar:?]
        at qz.utils.ArgParser.processInstallerArgs(Unknown Source) ~[qz-tray.jar:?]
        at qz.utils.ArgParser.intercept(Unknown Source) ~[qz-tray.jar:?]
        at qz.App.main(Unknown Source) ~[qz-tray.jar:?]
Installation failed during install step.  Please check log for details.
```

Any help?

**Comment by tresf** [comment]
This is a bit of a spinoff of #968.  It's not the same bug, but I believe it's the same cause where Windows is not reporting paths that are documented by Microsoft.

We can probably suppress this error, but what's a bit alarming is... why the hell is the Start Menu coming back as `<unknown>`?

**Comment by tresf** [comment]
> This is a bit of a spinoff of https://github.com/qzind/tray/issues/968. It's not the same bug, but I believe it's the same cause where Windows is not reporting paths that are documented by Microsoft.

Hmm... scratch that, the logs show the path is calculated just fine.  Still investigating...

**Comment by tresf** [comment]
Fixed via https://github.com/qzind/tray/commit/521e18614041032db43e50bc93ae0e63110a0be9.  It appears upstream broke the old (now deprecated) API.  Switching to the new API fixes it.

Upstream bug report: https://github.com/DmitriiShamrikov/mslinks/issues/35
